Repository woowacourse-teams/2023-yozm-cafe, pull requests merged in 2023-09, with the labels that each got.

#428 flyway 적용
  server/build.gradle
  server/src/main/resources/application.properties
  server/src/main/resources/db/migration/V20230901153300__init.sql
  server/src/main/resources/flyway/createSql.sh
Labels: BE, 우선순위:🟠높음

#432 flyway적용 코드 Main에 싱크 맞추기
  server/build.gradle
  server/src/main/resources/application-test.properties
  server/src/main/resources/application.properties
  server/src/main/resources/db/migration/V20230901153300__init.sql
  server/src/main/resources/flyway/createSql.sh
Labels: BE, 우선순위:🟡보통

#434 기존 테스트 환경 TestContainers로 리팩토링
  server/build.gradle
  server/src/main/resources/application-test.properties
  server/src/main/resources/db/migration/V20230901153300__init.sql
  server/src/test/java/com/project/yozmcafe/BaseTest.java
  server/src/test/java/com/project/yozmcafe/DataInitializer.java
  server/src/test/java/com/project/yozmcafe/YozmCafeApplicationTests.java
  server/src/test/java/com/project/yozmcafe/controller/BaseControllerTest.java
  server/src/test/java/com/project/yozmcafe/controller/LoginArgumentResolverTest.java
  server/src/test/java/com/project/yozmcafe/domain/cafe/CafeRepositoryTest.java
  server/src/test/java/com/project/yozmcafe/domain/member/MemberRepositoryTest.java
  server/src/test/java/com/project/yozmcafe/service/CafeAdminServiceTest.java
  server/src/test/java/com/project/yozmcafe/service/CafeServiceTest.java
  server/src/test/java/com/project/yozmcafe/service/ImageServiceTest.java
  server/src/test/java/com/project/yozmcafe/service/LikedCafeServiceTest.java
  server/src/test/java/com/project/yozmcafe/service/MemberServiceTest.java
  server/src/test/java/com/project/yozmcafe/service/MenuServiceTest.java
  server/src/test/java/com/project/yozmcafe/service/UnViewedCafeServiceTest.java
  server/src/test/java/com/project/yozmcafe/service/auth/AuthServiceTest.java
  server/src/test/java/com/project/yozmcafe/service/auth/OAuthProviderTest.java
  server/src/test/resources/truncate.sql
Labels: BE

#437 성능 측정용 로깅 필터 추가
  server/src/main/java/com/project/yozmcafe/config/FilterConfiguration.java
  server/src/main/java/com/project/yozmcafe/config/HibernateConfiguration.java
  server/src/main/java/com/project/yozmcafe/config/WebConfiguration.java
  server/src/main/java/com/project/yozmcafe/controller/StringToOAuthProviderConverter.java
  server/src/main/java/com/project/yozmcafe/controller/auth/AuthController.java
  server/src/main/java/com/project/yozmcafe/controller/filter/LatencyLoggingFilter.java
  server/src/main/java/com/project/yozmcafe/controller/filter/LatencyRecorder.java
  server/src/main/java/com/project/yozmcafe/controller/filter/QueryCounter.java
  server/src/main/java/com/project/yozmcafe/controller/filter/QueryInspector.java
  server/src/test/java/com/project/yozmcafe/controller/AuthControllerTest.java
  server/src/test/java/com/project/yozmcafe/controller/filter/LatencyRecorderTest.java
  server/src/test/java/com/project/yozmcafe/controller/filter/QueryInspectorTest.java
Labels: BE

#446 성능 측정용 필터를 구현한다
  server/src/main/java/com/project/yozmcafe/config/FilterConfiguration.java
  server/src/main/java/com/project/yozmcafe/config/HibernateConfiguration.java
  server/src/main/java/com/project/yozmcafe/config/WebConfiguration.java
  server/src/main/java/com/project/yozmcafe/controller/StringToOAuthProviderConverter.java
  server/src/main/java/com/project/yozmcafe/controller/auth/AuthController.java
  server/src/main/java/com/project/yozmcafe/controller/filter/LatencyLoggingFilter.java
  server/src/main/java/com/project/yozmcafe/controller/filter/LatencyRecorder.java
  server/src/main/java/com/project/yozmcafe/controller/filter/QueryCounter.java
  server/src/main/java/com/project/yozmcafe/controller/filter/QueryInspector.java
  server/src/test/java/com/project/yozmcafe/controller/AuthControllerTest.java
  server/src/test/java/com/project/yozmcafe/controller/filter/LatencyRecorderTest.java
  server/src/test/java/com/project/yozmcafe/controller/filter/QueryInspectorTest.java
Labels: BE

#441 n+1 개선
  server/src/main/java/com/project/yozmcafe/domain/cafe/CafeRepository.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/Images.java
  server/src/main/java/com/project/yozmcafe/domain/member/MemberRepository.java
  server/src/main/java/com/project/yozmcafe/domain/menu/MenuBoardRepository.java
  server/src/main/java/com/project/yozmcafe/domain/menu/MenuRepository.java
  server/src/main/resources/application.properties
  server/src/test/java/com/project/yozmcafe/domain/cafe/CafeRepositoryTest.java
Labels: BE, 우선순위:🟡보통, 카테고리:리팩토링🪚

#447 이미지 리사이즈 성능개선 및 이미지 서비스 리팩토링
  server/src/main/java/com/project/yozmcafe/controller/CafeAdminController.java
  server/src/main/java/com/project/yozmcafe/domain/resizedimage/ImageResizer.java
  server/src/main/java/com/project/yozmcafe/service/ImageService.java
  server/src/main/java/com/project/yozmcafe/service/MenuService.java
  server/src/test/java/com/project/yozmcafe/domain/ImageResizerTest.java
  server/src/test/java/com/project/yozmcafe/service/ImageServiceTest.java
Labels: BE, 우선순위:🟡보통, 카테고리:리팩토링🪚

#465 정적 리소스 assets 폴더로 이동
  client/public/assets/favicon.ico
  client/public/assets/ios.png
  client/public/assets/thumbnail-image.png
Labels: FE, 우선순위:🟡보통, 카테고리:리팩토링🪚

#466 번들 사이즈 최적화
  client/index.html
  client/package.json
  client/public/assets/logo.svg
  client/src/components/LoginModal.tsx
  client/src/components/Logo.stories.tsx
  client/src/components/Logo.tsx
  client/src/components/Navbar.tsx
  client/src/index.tsx
  client/src/pages/AuthPage.tsx
  client/src/pages/CafePage.tsx
  client/src/pages/HomePage.tsx
  client/src/pages/LikedCafeDetailPage.tsx
  client/src/pages/Loading.tsx
  client/src/pages/LoadingPage.tsx
  client/src/pages/MyProfilePage.tsx
  client/src/pages/NotFound.tsx
  client/src/pages/NotFoundPage.tsx
  client/src/pages/RankPage.tsx
  client/src/pages/TestAuthorizationCodePage.tsx
  client/src/router.tsx
  client/src/styles/GlobalStyle.ts
  client/tsconfig.json
  client/webpack.common.js
  client/webpack.development.js
  client/webpack.production.js
  client/yarn.lock
Labels: FE, 우선순위:🟠높음, 카테고리:리팩토링🪚, 카테고리:최적화🚀

#459 JavaScript로 제어하는 스크롤 스냅 구현
  client/src/components/CafeCard.tsx
  client/src/components/ScrollSnapContainer.tsx
  client/src/pages/HomePage.tsx
  client/src/styles/GlobalStyle.ts
  client/src/utils/timingFunctions.ts
Labels: 카테고리:기능🛠️, FE, FE:홈화면, 우선순위:🟠높음, 카테고리:리팩토링🪚, 카테고리:최적화🚀

#455 지도 기능
  server/build.gradle
  server/src/main/java/com/project/yozmcafe/controller/CafeAdminController.java
  server/src/main/java/com/project/yozmcafe/controller/LocationController.java
  server/src/main/java/com/project/yozmcafe/controller/dto/cafe/CafeCoordinateRequest.java
  server/src/main/java/com/project/yozmcafe/controller/dto/cafe/CafeLocationRequest.java
  server/src/main/java/com/project/yozmcafe/controller/dto/cafe/CafeLocationResponse.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/GeometryGenerator.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/Images.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/coordinate/CafeCoordinate.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/coordinate/CafeCoordinateRepository.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/coordinate/dto/CafePinDto.java
  server/src/main/java/com/project/yozmcafe/service/CafeAdminService.java
  server/src/main/java/com/project/yozmcafe/service/LocationService.java
  server/src/main/resources/application.properties
  server/src/main/resources/db/migration/V20230914151731__add_point_column.sql
  server/src/test/java/com/project/yozmcafe/controller/CafeAdminControllerTest.java
  server/src/test/java/com/project/yozmcafe/controller/LocationControllerTest.java
  server/src/test/java/com/project/yozmcafe/domain/cafe/CafeCoordinateTest.java
  server/src/test/java/com/project/yozmcafe/domain/cafe/GeometryGeneratorTest.java
  server/src/test/java/com/project/yozmcafe/domain/cafe/coordinate/CafeCoordinateRepositoryTest.java
  server/src/test/java/com/project/yozmcafe/service/CafeAdminServiceTest.java
  server/src/test/java/com/project/yozmcafe/service/LocationServiceTest.java
Labels: 카테고리:기능🛠️, BE, 우선순위:🟡보통

#461 OSIV false
  server/src/main/java/com/project/yozmcafe/controller/CafeController.java
  server/src/main/java/com/project/yozmcafe/controller/LikedCafeController.java
  server/src/main/java/com/project/yozmcafe/controller/LoginArgumentResolver.java
  server/src/main/java/com/project/yozmcafe/controller/LoginUser.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/Images.java
  server/src/main/java/com/project/yozmcafe/service/CafeService.java
  server/src/main/java/com/project/yozmcafe/service/LikedCafeService.java
  server/src/main/resources/application.properties
  server/src/test/java/com/project/yozmcafe/controller/CafeControllerTest.java
  server/src/test/java/com/project/yozmcafe/service/CafeServiceTest.java
  server/src/test/java/com/project/yozmcafe/service/LikedCafeServiceTest.java
Labels: BE

#487 osiv main merge
  server/src/main/java/com/project/yozmcafe/controller/CafeController.java
  server/src/main/java/com/project/yozmcafe/controller/LikedCafeController.java
  server/src/main/java/com/project/yozmcafe/controller/LoginArgumentResolver.java
  server/src/main/java/com/project/yozmcafe/controller/LoginUser.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/Images.java
  server/src/main/java/com/project/yozmcafe/service/CafeService.java
  server/src/main/java/com/project/yozmcafe/service/LikedCafeService.java
  server/src/main/resources/application.properties
  server/src/test/java/com/project/yozmcafe/controller/CafeControllerTest.java
  server/src/test/java/com/project/yozmcafe/service/CafeServiceTest.java
  server/src/test/java/com/project/yozmcafe/service/LikedCafeServiceTest.java
Labels: BE, 우선순위:🟡보통, 카테고리:리팩토링🪚

#483 불필요한 `console.log` 삭제
  client/src/components/ScrollSnapContainer.tsx
Labels: 카테고리:버그👾, FE, FE:홈화면, 우선순위:🟠높음

#443 카페 검색 기능 개발
  server/build.gradle
  server/src/main/java/com/project/yozmcafe/config/QueryDslConfig.java
  server/src/main/java/com/project/yozmcafe/controller/CafeController.java
  server/src/main/java/com/project/yozmcafe/controller/LikedCafeController.java
  server/src/main/java/com/project/yozmcafe/controller/dto/cafe/CafeSearchRequest.java
  server/src/main/java/com/project/yozmcafe/controller/dto/cafe/CafeSearchResponse.java
  server/src/main/java/com/project/yozmcafe/controller/dto/cafe/CafeThumbnailResponse.java
  server/src/main/java/com/project/yozmcafe/controller/dto/cafe/LikedCafeThumbnailResponse.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/CafeCustomRepository.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/CafeCustomRepositoryImpl.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/CafeRepository.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/CustomFunctionContributor.java
  server/src/main/java/com/project/yozmcafe/domain/member/Member.java
  server/src/main/java/com/project/yozmcafe/service/CafeService.java
  server/src/main/java/com/project/yozmcafe/service/LikedCafeService.java
  server/src/main/resources/META-INF/services/org.hibernate.boot.model.FunctionContributor
  server/src/main/resources/db/migration/V20230925125500__full_text_idx.sql
  server/src/test/java/com/project/yozmcafe/controller/CafeControllerTest.java
  server/src/test/java/com/project/yozmcafe/domain/cafe/CafeCustomRepositoryImplTest.java
  server/src/test/java/com/project/yozmcafe/domain/member/MemberTest.java
  server/src/test/java/com/project/yozmcafe/fixture/Fixture.java
  server/src/test/java/com/project/yozmcafe/service/CafeServiceTest.java
  server/src/test/java/com/project/yozmcafe/service/LikedCafeServiceTest.java
Labels: 카테고리:기능🛠️, BE

#468 카페 이미지 Fetch Join 시 Inner Join 하도록 변경
  server/build.gradle
  server/src/main/java/com/project/yozmcafe/config/QueryDslConfig.java
  server/src/main/java/com/project/yozmcafe/controller/CafeController.java
  server/src/main/java/com/project/yozmcafe/controller/LikedCafeController.java
  server/src/main/java/com/project/yozmcafe/domain/CafeRankGenerator.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/Cafe.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/CafeRepository.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/Detail.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/Images.java
  server/src/main/java/com/project/yozmcafe/domain/member/Member.java
  server/src/main/java/com/project/yozmcafe/domain/member/MemberRepository.java
  server/src/main/java/com/project/yozmcafe/exception/ErrorCode.java
  server/src/main/java/com/project/yozmcafe/service/CafeService.java
  server/src/main/resources/application-test.properties
  server/src/test/java/com/project/yozmcafe/controller/CafeControllerTest.java
  server/src/test/java/com/project/yozmcafe/domain/cafe/CafeTest.java
  server/src/test/java/com/project/yozmcafe/domain/member/MemberTest.java
  server/src/test/java/com/project/yozmcafe/service/CafeRankGeneratorTest.java
  server/src/test/java/com/project/yozmcafe/service/CafeServiceTest.java
  server/src/test/java/com/project/yozmcafe/service/auth/AuthServiceTest.java
Labels: BE

#491 Offset 관련 에러 해결
  server/src/main/java/com/project/yozmcafe/domain/cafe/Images.java
  server/src/main/java/com/project/yozmcafe/domain/member/Member.java
  server/src/test/java/com/project/yozmcafe/domain/member/MemberTest.java
Labels: 카테고리:버그👾, BE

#454 db replication, 라우팅 추가
  server/docker-compose.yml
  server/src/main/java/com/project/yozmcafe/config/datasource/DataSourceConfig.java
  server/src/main/java/com/project/yozmcafe/config/datasource/RoutingDataSource.java
  server/src/main/resources/application-test.properties
  server/src/main/resources/application-test.yaml
  server/src/main/resources/application.properties
  server/src/main/resources/application.yaml
Labels: BE

#492 카페 이미지 Outer Join -> Inner Join (카페 이미지 최소 1개 이상 포함시키기)
  server/build.gradle
  server/src/main/java/com/project/yozmcafe/config/QueryDslConfig.java
  server/src/main/java/com/project/yozmcafe/controller/CafeController.java
  server/src/main/java/com/project/yozmcafe/controller/LikedCafeController.java
  server/src/main/java/com/project/yozmcafe/controller/dto/cafe/CafeSearchRequest.java
  server/src/main/java/com/project/yozmcafe/controller/dto/cafe/CafeSearchResponse.java
  server/src/main/java/com/project/yozmcafe/controller/dto/cafe/CafeThumbnailResponse.java
  server/src/main/java/com/project/yozmcafe/controller/dto/cafe/LikedCafeThumbnailResponse.java
  server/src/main/java/com/project/yozmcafe/domain/CafeRankGenerator.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/Cafe.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/CafeCustomRepository.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/CafeCustomRepositoryImpl.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/CafeRepository.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/CustomFunctionContributor.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/Detail.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/Images.java
  server/src/main/java/com/project/yozmcafe/domain/member/Member.java
  server/src/main/java/com/project/yozmcafe/domain/member/MemberRepository.java
  server/src/main/java/com/project/yozmcafe/exception/ErrorCode.java
  server/src/main/java/com/project/yozmcafe/service/CafeService.java
  server/src/main/java/com/project/yozmcafe/service/LikedCafeService.java
  server/src/main/resources/META-INF/services/org.hibernate.boot.model.FunctionContributor
  server/src/main/resources/application-test.properties
  server/src/main/resources/db/migration/V20230925125500__full_text_idx.sql
  server/src/test/java/com/project/yozmcafe/controller/CafeControllerTest.java
  server/src/test/java/com/project/yozmcafe/domain/cafe/CafeCustomRepositoryImplTest.java
  server/src/test/java/com/project/yozmcafe/domain/cafe/CafeTest.java
  server/src/test/java/com/project/yozmcafe/domain/member/MemberTest.java
  server/src/test/java/com/project/yozmcafe/fixture/Fixture.java
  server/src/test/java/com/project/yozmcafe/service/CafeRankGeneratorTest.java
  server/src/test/java/com/project/yozmcafe/service/CafeServiceTest.java
  server/src/test/java/com/project/yozmcafe/service/LikedCafeServiceTest.java
  server/src/test/java/com/project/yozmcafe/service/auth/AuthServiceTest.java
Labels: BE

#486 새로운 유저 로그인 시 발생하는 불필요한 쿼리 제거
  server/src/main/java/com/project/yozmcafe/domain/member/Member.java
  server/src/main/java/com/project/yozmcafe/service/auth/AuthService.java
  server/src/main/resources/db/migration/V20230924132258__add_created_at_to_member.sql
  server/src/test/java/com/project/yozmcafe/controller/AuthControllerTest.java
Labels: BE, 우선순위:🟡보통, 카테고리:리팩토링🪚

#509 유틸을 통해 리소스 URL을 생성할 수 있도록 리팩토링
  client/public/images/100/cafe-menu-image-1.jpg
  client/public/images/100/cafe-menu-image-2.avif
  client/public/images/500/cafe-image-1.png
  client/public/images/500/cafe-image-2.png
  client/public/images/500/cafe-image-3.png
  client/public/images/500/cafe-image-4.png
  client/public/images/500/cafe-image-5.png
  client/public/images/original/cafe-menu-board-image-1.jpg
  client/public/images/original/cafe-menu-board-image-2.jpg
  client/public/images/original/cafe-menu-board-image-3.jpg
  client/src/components/CafeCard.tsx
  client/src/components/CafeMenuBottomSheet.tsx
  client/src/components/CafeMenuList.tsx
  client/src/components/CafeMenuMiniList.tsx
  client/src/components/ImageModal.tsx
  client/src/components/LikedCafeList.tsx
  client/src/components/LoginModal.tsx
  client/src/components/Navbar.tsx
  client/src/components/RankCard.tsx
  client/src/data/mockData.ts
  client/src/environment.ts
  client/src/utils/Image.ts
  client/src/utils/Resource.ts
Labels: 카테고리:버그👾, FE, 우선순위:🟠높음, 카테고리:리팩토링🪚

#476 불필요한 이미지 fetch 최소화 및 이미지 fetch 우선순위 조정
  client/src/components/CafeCard.tsx
  client/src/components/ScrollSnapContainer.tsx
Labels: FE, FE:홈화면, 우선순위:🟠높음, 카테고리:최적화🚀

#511 불필요한 이미지 fetch 최소화 및 이미지 fetch 우선순위 조정
  client/src/components/CafeCard.tsx
  client/src/components/ScrollSnapContainer.tsx
Labels: FE, FE:홈화면, 우선순위:🟠높음, 카테고리:최적화🚀

#504 MSW, 개발 서버 등 API 서버를 쉽게 변경할 수 있는 명령줄(CLI) 옵션 지원
  client/package.json
  client/scripts/start.js
  client/webpack.development.js
Labels: FE, 카테고리:인프라🏗️, 우선순위:🟡보통

#519 MSW, 개발 서버 등 API 서버를 쉽게 변경할 수 있는 명령줄(CLI) 옵션 지원
  client/package.json
  client/scripts/start.js
  client/webpack.development.js
Labels: FE, 카테고리:인프라🏗️, 우선순위:🟡보통

#514 키보드 방향키로 스와이프할 수 있도록 구현
  client/src/components/ScrollSnapContainer.tsx
  client/src/shims/useEffectEvent.ts
Labels: 카테고리:기능🛠️, FE, FE:홈화면, 우선순위:🟡보통
