Repository woowacourse-teams/2023-yozm-cafe, pull requests merged in 2023-10, with the labels that each got.

#526 Toast 컴포넌트를 제작한다.
  client/src/App.tsx
  client/src/context/ToastContext.tsx
Labels: 카테고리:기능🛠️, FE, FE:홈화면, FE:로그인 화면, FE:프로필 화면, 우선순위:🟡보통, FE:좋아요 랭킹 화면, FE:지도 화면, FE:검색 화면

#522 로딩 중을 표시하기 위한 컴포넌트를 제작한다.
  client/src/components/LoadingBar.tsx
Labels: 카테고리:기능🛠️, FE, FE:홈화면, FE:로그인 화면, FE:프로필 화면, 우선순위:🟡보통, FE:좋아요 랭킹 화면, FE:지도 화면, FE:검색 화면

#524 에러를 표시하기 위한 컴포넌트를 제작한다.
  client/src/pages/ErrorPage.tsx
  client/src/styles/theme.ts
Labels: 카테고리:기능🛠️, FE, FE:홈화면, FE:로그인 화면, FE:프로필 화면, 우선순위:🟡보통, FE:좋아요 랭킹 화면, FE:지도 화면, FE:검색 화면

#506 카페의 위치를 보여줄 수 있는 지도를 구현
  client/package.json
  client/public/assets/coffee-icon.png
  client/public/assets/current-position-icon.png
  client/src/client.ts
  client/src/components/Button.tsx
  client/src/components/CafeActionBar.tsx
  client/src/components/CafeDetailBottomSheet.tsx
  client/src/components/CafeMap.tsx
  client/src/components/CafeMarkers.tsx
  client/src/components/CafeMarkersContainer.tsx
  client/src/components/CafeMenuBottomSheet.tsx
  client/src/components/ImageModal.tsx
  client/src/components/LoginButton.tsx
  client/src/components/LoginModal.tsx
  client/src/components/UserMarker.tsx
  client/src/constants/index.ts
  client/src/data/mockData.ts
  client/src/hooks/useCafesNearLocation.ts
  client/src/hooks/useCurrentPosition.ts
  client/src/hooks/useObservable.ts
  client/src/mocks/handlers.ts
  client/src/pages/CafeMapPage.tsx
  client/src/router.tsx
  client/src/styles/GlobalStyle.ts
  client/src/styles/theme.ts
  client/src/types/index.ts
  client/src/utils/Observable.ts
  client/src/utils/mapUtils.ts
  client/yarn.lock
Labels: FE, 작업:페어, 우선순위:🟠높음, FE:지도 화면

#528 `yarn.lock` 파일 업데이트
  client/yarn.lock
Labels: 카테고리:버그👾, FE, 우선순위:🟠높음

#495 웹앱 대응을 위한 favicons-webpack-plugin 적용
  client/index.html
  client/package.json
  client/src/assets/icon.svg
  client/webpack.common.js
  client/yarn.lock
Labels: 카테고리:기능🛠️, FE, 우선순위:🟢낮음

#529 웹앱 대응을 위한 favicons-webpack-plugin 적용
  client/index.html
  client/package.json
  client/src/assets/icon.svg
  client/webpack.common.js
  client/yarn.lock
Labels: 카테고리:기능🛠️, FE, 우선순위:🟢낮음

#515 카페 이미지가 drag & drop 되지 않도록 수정
  client/src/components/CafeCard.tsx
  client/src/components/ScrollSnapContainer.tsx
Labels: 카테고리:버그👾, FE, FE:홈화면, 우선순위:🟡보통

#530 카페 이미지가 drag & drop 되지 않도록 수정
  client/src/components/CafeCard.tsx
  client/src/components/ScrollSnapContainer.tsx
Labels: 카테고리:버그👾, FE, FE:홈화면, 우선순위:🟡보통

#520 키보드 방향키로 스와이프할 수 있도록 구현
  client/src/components/ScrollSnapContainer.tsx
  client/src/shims/useEffectEvent.ts
Labels: 카테고리:기능🛠️, FE, FE:홈화면, 우선순위:🟡보통

#517 모달에서 ScrollSnapContainer의 스와이프가 동작하는 오류 수정
  client/src/components/CafeDetailBottomSheet.tsx
  client/src/components/CafeMenuBottomSheet.tsx
  client/src/components/ImageModal.tsx
  client/src/hooks/useScrollSnapGuard.ts
Labels: 카테고리:버그👾, FE, FE:홈화면, 우선순위:🟠높음

#533 모달에서 ScrollSnapContainer의 스와이프가 동작하는 오류 수정
  client/src/components/CafeDetailBottomSheet.tsx
  client/src/components/CafeMenuBottomSheet.tsx
  client/src/components/ImageModal.tsx
  client/src/hooks/useScrollSnapGuard.ts
Labels: 카테고리:버그👾, FE, FE:홈화면, 우선순위:🟠높음

#534 `yarn.lock` 파일 업데이트
  client/yarn.lock
Labels: 카테고리:버그👾, FE, 우선순위:🟠높음

#501 storybook이 켜지지 않는 오류 해결 및 msw 적용
  client/.babelrc.js
  client/.storybook/main.ts
  client/.storybook/preview.tsx
  client/.storybook/webpack.config.js
  client/package.json
  client/public/mockServiceWorker.js
  client/src/index.tsx
  client/src/mocks/handlers.ts
  client/src/mocks/worker.ts
  client/webpack.common.js
  client/webpack.production.js
  client/yarn.lock
Labels: 카테고리:버그👾, FE, 우선순위:🟡보통, 카테고리:리팩토링🪚, 카테고리:테스트⚗️

#535 storybook이 켜지지 않는 오류 해결 및 msw 적용
  client/.babelrc.js
  client/.storybook/main.ts
  client/.storybook/preview.tsx
  client/.storybook/webpack.config.js
  client/package.json
  client/public/mockServiceWorker.js
  client/src/index.tsx
  client/src/mocks/handlers.ts
  client/src/mocks/worker.ts
  client/webpack.common.js
  client/webpack.production.js
  client/yarn.lock
Labels: 카테고리:버그👾, FE, 우선순위:🟡보통, 카테고리:리팩토링🪚, 카테고리:테스트⚗️

#490 검색 기능 구현
  client/src/client.ts
  client/src/components/Button.tsx
  client/src/components/Navbar.tsx
  client/src/components/SearchInput.tsx
  client/src/hooks/useSearchCafes.ts
  client/src/mocks/handlers.ts
  client/src/pages/SearchPage.tsx
  client/src/router.tsx
  client/src/styles/ResetStyle.ts
  client/src/types/index.ts
Labels: 카테고리:기능🛠️, FE, 우선순위:🟡보통, FE:검색 화면

#536 검색 기능 구현
  client/src/client.ts
  client/src/components/Button.tsx
  client/src/components/Navbar.tsx
  client/src/components/SearchInput.tsx
  client/src/hooks/useSearchCafes.ts
  client/src/mocks/handlers.ts
  client/src/pages/SearchPage.tsx
  client/src/router.tsx
  client/src/styles/ResetStyle.ts
  client/src/types/index.ts
Labels: 카테고리:기능🛠️, FE, 우선순위:🟡보통, FE:검색 화면

#537 npm으로 마이그레이션
  client/.npmrc
  client/.nvmrc
  client/package-lock.json
  client/package.json
  client/src/pages/MyProfilePage.tsx
  client/yarn.lock
Labels: FE, 제안🙏, 카테고리:인프라🏗️, 우선순위:🟠높음

#538 npm으로 마이그레이션
  client/.npmrc
  client/.nvmrc
  client/package-lock.json
  client/package.json
  client/src/pages/MyProfilePage.tsx
  client/yarn.lock
Labels: FE, 제안🙏, 카테고리:인프라🏗️, 우선순위:🟠높음

#543 DataInitializer에서 불필요한 커넥션을 제거한다
  server/src/test/java/com/project/yozmcafe/DataInitializer.java
Labels: BE

#554 DataInitializer에서 불필요한 커넥션 제거
  server/src/test/java/com/project/yozmcafe/DataInitializer.java
Labels: BE

#545 테스트 성능개선 및 인수테스트 리팩토링
  server/src/main/resources/application-test.yaml
  server/src/test/java/com/project/yozmcafe/controller/AuthControllerTest.java
  server/src/test/java/com/project/yozmcafe/controller/BaseControllerTest.java
  server/src/test/java/com/project/yozmcafe/controller/CafeAdminControllerTest.java
  server/src/test/java/com/project/yozmcafe/controller/CafeControllerTest.java
  server/src/test/java/com/project/yozmcafe/controller/LikedCafeControllerTest.java
  server/src/test/java/com/project/yozmcafe/controller/LoginArgumentResolverTest.java
  server/src/test/java/com/project/yozmcafe/controller/MemberControllerTest.java
  server/src/test/java/com/project/yozmcafe/controller/MenuControllerTest.java
  server/src/test/java/com/project/yozmcafe/controller/admin/AdminDocuments.java
  server/src/test/java/com/project/yozmcafe/controller/admin/CafeAdminControllerTest.java
  server/src/test/java/com/project/yozmcafe/controller/auth/AuthControllerTest.java
  server/src/test/java/com/project/yozmcafe/controller/auth/AuthDocuments.java
  server/src/test/java/com/project/yozmcafe/controller/cafe/CafeControllerTest.java
  server/src/test/java/com/project/yozmcafe/controller/cafe/CafeDocuments.java
  server/src/test/java/com/project/yozmcafe/controller/like/LikeCafeDocuments.java
  server/src/test/java/com/project/yozmcafe/controller/like/LikedCafeControllerTest.java
  server/src/test/java/com/project/yozmcafe/controller/location/LocationControllerTest.java
  server/src/test/java/com/project/yozmcafe/controller/location/LocationDocuments.java
  server/src/test/java/com/project/yozmcafe/controller/member/MemberControllerTest.java
  server/src/test/java/com/project/yozmcafe/controller/member/MemberDocuments.java
  server/src/test/java/com/project/yozmcafe/controller/menu/MenuControllerTest.java
  server/src/test/java/com/project/yozmcafe/controller/menu/MenuDocuments.java
  server/src/test/java/com/project/yozmcafe/service/BaseServiceTest.java
  server/src/test/java/com/project/yozmcafe/service/CafeAdminServiceTest.java
  server/src/test/java/com/project/yozmcafe/service/CafeServiceTest.java
  server/src/test/java/com/project/yozmcafe/service/ImageServiceTest.java
  server/src/test/java/com/project/yozmcafe/service/LikedCafeServiceTest.java
  server/src/test/java/com/project/yozmcafe/service/LocationServiceTest.java
  server/src/test/java/com/project/yozmcafe/service/MemberServiceTest.java
  server/src/test/java/com/project/yozmcafe/service/MenuServiceTest.java
  server/src/test/java/com/project/yozmcafe/service/UnViewedCafeServiceTest.java
  server/src/test/java/com/project/yozmcafe/service/auth/AuthServiceTest.java
  server/src/test/java/com/project/yozmcafe/service/auth/OAuthProviderTest.java
  server/src/test/java/com/project/yozmcafe/util/AcceptanceContext.java
Labels: BE, 우선순위:🟡보통, 카테고리:리팩토링🪚, 카테고리:테스트⚗️, 카테고리:최적화🚀

#548 지도 검색기능 jpql로 리팩토링
  server/src/main/java/com/project/yozmcafe/domain/cafe/GeometryGenerator.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/coordinate/CafeCoordinateRepository.java
  server/src/main/java/com/project/yozmcafe/service/LocationService.java
  server/src/test/java/com/project/yozmcafe/domain/cafe/GeometryGeneratorTest.java
  server/src/test/java/com/project/yozmcafe/domain/cafe/coordinate/CafeCoordinateRepositoryTest.java
Labels: BE, 우선순위:🟡보통, 카테고리:리팩토링🪚

#552 webpack.common.js 에 `publicPath: '/'` 추가
  client/webpack.common.js
  client/webpack.production.js
Labels: 카테고리:버그👾, FE, 우선순위:🟡보통

#560 모달 아이콘의 지도 아이콘을 네이버 지도로 수정
  client/public/assets/naver-map-icon.png
  client/src/components/CafeDetailBottomSheet.tsx
Labels: FE, FE:홈화면, 우선순위:🟡보통, 카테고리:리팩토링🪚

#561 webpack.common.js 에 `publicPath: '/'` 추가
  client/webpack.common.js
  client/webpack.production.js
Labels: 카테고리:버그👾, FE, 우선순위:🟡보통

#546 에러 핸들링을 위한 컴포넌트 추가 및 적용
  client/src/App.tsx
  client/src/client.ts
  client/src/components/CafeDetailBottomSheet.tsx
  client/src/components/CafeMenuBottomSheet.tsx
  client/src/components/ErrorBoundary.tsx
  client/src/components/ErrorRetryPrompt.tsx
  client/src/components/QueryErrorBoundary.tsx
  client/src/context/ToastContext.tsx
  client/src/errors/APIError.ts
  client/src/errors/AppError.ts
  client/src/errors/NetworkError.ts
  client/src/hooks/useSilentLink.ts
  client/src/pages/ErrorPage.tsx
  client/src/pages/NotFoundPage.tsx
  client/src/pages/Root.tsx
  client/src/router.tsx
  client/src/types/index.ts
Labels: 카테고리:기능🛠️, FE, 작업:몹, 우선순위:🟡보통, 카테고리:리팩토링🪚

#568 에러 핸들링을 위한 컴포넌트 추가 및 적용
  client/src/App.tsx
  client/src/client.ts
  client/src/components/CafeDetailBottomSheet.tsx
  client/src/components/CafeMenuBottomSheet.tsx
  client/src/components/ErrorBoundary.tsx
  client/src/components/ErrorRetryPrompt.tsx
  client/src/components/QueryErrorBoundary.tsx
  client/src/context/ToastContext.tsx
  client/src/errors/APIError.ts
  client/src/errors/AppError.ts
  client/src/errors/NetworkError.ts
  client/src/hooks/useSilentLink.ts
  client/src/pages/ErrorPage.tsx
  client/src/pages/NotFoundPage.tsx
  client/src/pages/Root.tsx
  client/src/router.tsx
  client/src/types/index.ts
Labels: 카테고리:기능🛠️, FE, 작업:몹, 우선순위:🟡보통, 카테고리:리팩토링🪚

#513 ScrollSnap Overhaul
  client/src/components/CafeDetailBottomSheet.tsx
  client/src/components/CafeMenuBottomSheet.tsx
  client/src/components/ImageModal.tsx
  client/src/components/ScrollSnap/components/ScrollSnap.tsx
  client/src/components/ScrollSnap/components/ScrollSnapCSS/ScrollSnapCSS.tsx
  client/src/components/ScrollSnap/components/ScrollSnapCSS/ScrollSnapCSSItemList.tsx
  client/src/components/ScrollSnap/components/ScrollSnapImpl/ScrollSnapImpl.tsx
  client/src/components/ScrollSnap/components/ScrollSnapImpl/ScrollSnapImplItemList.tsx
  client/src/components/ScrollSnap/components/ScrollSnapItem.tsx
  client/src/components/ScrollSnap/hooks/useScrollSnapGuard.ts
  client/src/components/ScrollSnap/index.ts
  client/src/components/ScrollSnap/types.ts
  client/src/pages/HomePage.tsx
Labels: 카테고리:버그👾, FE, FE:홈화면, 우선순위:🟡보통

#572 CafeActionBar의 구현을 CafeCard로 이동
  client/src/components/CafeActionBar.tsx
  client/src/components/CafeCard.tsx
Labels: FE, FE:홈화면, 우선순위:🟡보통, 카테고리:리팩토링🪚

#570 홈 화면의 아이콘 버튼 레이아웃 조정 및 리팩토링
  client/src/components/CafeActionBar.tsx
  client/src/components/CafeCard.tsx
  client/src/components/CafeSummary.tsx
  client/src/components/CommentButton.stories.tsx
  client/src/components/CommentButton.tsx
  client/src/components/IconButton.stories.tsx
  client/src/components/IconButton.tsx
  client/src/components/LikeButton.stories.tsx
  client/src/components/LikeButton.tsx
  client/src/components/ShareButton.tsx
  client/src/hooks/useClipboard.ts
Labels: 카테고리:버그👾, FE, FE:홈화면, 우선순위:🟡보통, 카테고리:리팩토링🪚

#541 UnViewedCafe batch insert 개선하기
  server/src/main/java/com/project/yozmcafe/config/CustomFunctionContributor.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/UnViewedCafeRepository.java
  server/src/main/java/com/project/yozmcafe/domain/member/Member.java
  server/src/main/java/com/project/yozmcafe/service/CafeRefillEvent.java
  server/src/main/java/com/project/yozmcafe/service/CafeRefillEventPublisher.java
  server/src/main/java/com/project/yozmcafe/service/CafeService.java
  server/src/main/java/com/project/yozmcafe/service/UnViewedCafeRefillListener.java
  server/src/main/java/com/project/yozmcafe/service/UnViewedCafeService.java
  server/src/main/java/com/project/yozmcafe/service/auth/AuthService.java
  server/src/main/resources/META-INF/services/org.hibernate.boot.model.FunctionContributor
  server/src/main/resources/application.yaml
  server/src/test/java/com/project/yozmcafe/domain/cafe/CafeCustomRepositoryImplTest.java
  server/src/test/java/com/project/yozmcafe/domain/cafe/UnViewedCafeRepositoryTest.java
  server/src/test/java/com/project/yozmcafe/service/BaseServiceTest.java
  server/src/test/java/com/project/yozmcafe/service/UnViewedCafeRefillListenerTest.java
  server/src/test/java/com/project/yozmcafe/service/UnViewedCafeServiceTest.java
  server/src/test/java/com/project/yozmcafe/service/auth/AuthServiceTest.java
Labels: BE, 우선순위:🟡보통

#567 Google 애널리틱스 4를 추가한다.
  client/index.html
  client/package-lock.json
  client/package.json
  client/src/components/CafeCard.tsx
  client/src/pages/HomePage.tsx
  client/src/pages/Root.tsx
  client/src/utils/GoogleAnalytics.ts
Labels: 카테고리:기능🛠️, FE, 작업:페어, 우선순위:🟡보통

#576 지도의 로딩중이라는 이미지를 로딩 컴포넌트로 수정한다.
  client/src/pages/CafeMapPage.tsx
Labels: 카테고리:기능🛠️, FE, 우선순위:🟡보통, FE:지도 화면

#577 지도의 로딩중이라는 이미지를 로딩 컴포넌트로 수정한다.
  client/src/pages/CafeMapPage.tsx
Labels: FE, 우선순위:🟡보통, 카테고리:리팩토링🪚, FE:지도 화면

#583 CSS scroll-snap 모드에서 카페가 한 번에 한 개씩 스와이프되도록 설정
  client/src/components/ScrollSnap/components/ScrollSnapCSS/ScrollSnapCSS.tsx
Labels: 카테고리:기능🛠️, FE, FE:홈화면, 우선순위:🟠높음

#584 아이폰에서 스와이프 시 새로고침이 되던 오류 수정
  client/src/styles/GlobalStyle.ts
Labels: 카테고리:버그👾, FE, FE:홈화면, 우선순위:🟠높음

#586 일부 화면 비율에서 컨텐츠가 잘리는 오류 수정
  client/src/components/CafeCard.tsx
Labels: 카테고리:버그👾, FE, FE:홈화면, 우선순위:🟠높음

#588 아이폰에서 버튼, 이미지 등의 컨텐츠가 스와이프 시 깜빡이거나 사라지는 오류 수정
  client/src/components/CafeCard.tsx
Labels: 카테고리:버그👾, FE, FE:홈화면, 우선순위:🟠높음

#589 아이폰에서 버튼, 이미지 등의 컨텐츠가 스와이프 시 깜빡이거나 사라지는 오류 수정
  client/src/components/CafeCard.tsx
Labels: 카테고리:버그👾, FE, FE:홈화면, 우선순위:🟠높음

#591 아이폰에서 상하좌우 동시에 스와이프되는 문제 수정
  client/src/components/ScrollSnap/components/ScrollSnap.tsx
Labels: 카테고리:버그👾, FE, FE:홈화면, 작업:페어, 우선순위:🟠높음

#593 아이폰에서 상하좌우 동시에 스와이프되는 문제 수정
  client/src/components/ScrollSnap/components/ScrollSnap.tsx
Labels: 카테고리:버그👾, FE, FE:홈화면, 작업:페어, 우선순위:🟠높음

#594 파이어폭스에서 스크롤바가 보이는 문제를 해결한다.
  client/src/styles/GlobalStyle.ts
Labels: 카테고리:버그👾, FE, FE:홈화면, FE:로그인 화면, FE:프로필 화면, 우선순위:🟡보통, FE:좋아요 랭킹 화면, FE:지도 화면, FE:검색 화면

#597 Scroll Snap 기능을 라이브러리로 분리 및 적용
  client/package-lock.json
  client/package.json
  client/src/components/CafeDetailBottomSheet.tsx
  client/src/components/CafeMenuBottomSheet.tsx
  client/src/components/ImageModal.tsx
  client/src/components/ScrollSnap/components/ScrollSnap.tsx
  client/src/components/ScrollSnap/components/ScrollSnapCSS/ScrollSnapCSS.tsx
  client/src/components/ScrollSnap/components/ScrollSnapCSS/ScrollSnapCSSItemList.tsx
  client/src/components/ScrollSnap/components/ScrollSnapImpl/ScrollSnapImpl.tsx
  client/src/components/ScrollSnap/components/ScrollSnapImpl/ScrollSnapImplItemList.tsx
  client/src/components/ScrollSnap/components/ScrollSnapItem.tsx
  client/src/components/ScrollSnap/hooks/useScrollSnapGuard.ts
  client/src/components/ScrollSnap/index.ts
  client/src/components/ScrollSnap/types.ts
  client/src/pages/HomePage.tsx
  client/src/utils/timingFunctions.ts
Labels: FE, FE:홈화면, 우선순위:🟡보통, 카테고리:리팩토링🪚

#598 Scroll Snap 기능을 라이브러리로 분리 및 적용
  client/package-lock.json
  client/package.json
  client/src/components/CafeDetailBottomSheet.tsx
  client/src/components/CafeMenuBottomSheet.tsx
  client/src/components/ImageModal.tsx
  client/src/components/ScrollSnap/components/ScrollSnap.tsx
  client/src/components/ScrollSnap/components/ScrollSnapCSS/ScrollSnapCSS.tsx
  client/src/components/ScrollSnap/components/ScrollSnapCSS/ScrollSnapCSSItemList.tsx
  client/src/components/ScrollSnap/components/ScrollSnapImpl/ScrollSnapImpl.tsx
  client/src/components/ScrollSnap/components/ScrollSnapImpl/ScrollSnapImplItemList.tsx
  client/src/components/ScrollSnap/components/ScrollSnapItem.tsx
  client/src/components/ScrollSnap/hooks/useScrollSnapGuard.ts
  client/src/components/ScrollSnap/index.ts
  client/src/components/ScrollSnap/types.ts
  client/src/pages/HomePage.tsx
  client/src/utils/timingFunctions.ts
Labels: FE, FE:홈화면, 우선순위:🟡보통, 카테고리:리팩토링🪚

#600 검색 페이지의 문구를 수정한다.
  client/src/pages/SearchPage.tsx
Labels: FE, 우선순위:🟡보통, 카테고리:리팩토링🪚, FE:검색 화면

#601 검색 페이지의 문구를 수정한다.
  client/src/pages/SearchPage.tsx
Labels: FE, 우선순위:🟡보통, 카테고리:리팩토링🪚, FE:검색 화면

#605 다수 버그 수정
  client/src/components/CafeDetailBottomSheet.tsx
  client/src/components/CafeMenuMiniList.tsx
  client/src/components/ImageModal.tsx
  client/src/components/OpeningHoursDetail.tsx
  client/src/styles/GlobalStyle.ts
Labels: 카테고리:버그👾, 카테고리:기능🛠️, FE, FE:홈화면, 우선순위:🟠높음

#607 다수 버그 수정
  client/src/components/CafeDetailBottomSheet.tsx
  client/src/components/CafeMenuMiniList.tsx
  client/src/components/ImageModal.tsx
  client/src/components/OpeningHoursDetail.tsx
  client/src/styles/GlobalStyle.ts
Labels: 카테고리:버그👾, 카테고리:기능🛠️, FE, FE:홈화면, 우선순위:🟠높음

#606 alert를 토스트 메세지로 대체
  client/src/components/CafeMap.tsx
Labels: 카테고리:기능🛠️, FE, 우선순위:🟡보통, FE:지도 화면

#608 alert를 토스트 메세지로 대체
  client/src/components/CafeMap.tsx
Labels: 카테고리:기능🛠️, FE, 우선순위:🟡보통, FE:지도 화면
