Repository woowacourse-teams/2023-yozm-cafe, pull requests merged in 2023-08, with the labels that each got.

#227 프로필 수정하기 버튼 삭제
  client/src/pages/MyProfile.tsx
Labels: FE, FE:프로필 화면, 우선순위:🟡보통

#224 로그인 상태가 영구적으로 저장되도록 구현
  client/src/context/AuthContext.tsx
  client/src/hooks/useAuth.ts
  client/src/hooks/usePersistedState.ts
Labels: 카테고리:기능🛠️, FE, 우선순위:🟠높음

#241 custom Exception 적용
  server/src/main/java/com/project/yozmcafe/controller/GlobalControllerAdvice.java
  server/src/main/java/com/project/yozmcafe/controller/LoginArgumentResolver.java
  server/src/main/java/com/project/yozmcafe/controller/auth/OAuthProvider.java
  server/src/main/java/com/project/yozmcafe/domain/auth/token/OAuthToken.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/Images.java
  server/src/main/java/com/project/yozmcafe/domain/member/Member.java
  server/src/main/java/com/project/yozmcafe/exception/BadRequestException.java
  server/src/main/java/com/project/yozmcafe/exception/BaseException.java
  server/src/main/java/com/project/yozmcafe/exception/ErrorCode.java
  server/src/main/java/com/project/yozmcafe/exception/OAuthException.java
  server/src/main/java/com/project/yozmcafe/exception/TokenException.java
  server/src/main/java/com/project/yozmcafe/service/MemberService.java
  server/src/main/java/com/project/yozmcafe/service/auth/JwtTokenProvider.java
  server/src/test/java/com/project/yozmcafe/controller/LoginArgumentResolverTest.java
  server/src/test/java/com/project/yozmcafe/controller/StringToOAuthProviderConverterTest.java
  server/src/test/java/com/project/yozmcafe/domain/auth/token/OAuthTokenTest.java
  server/src/test/java/com/project/yozmcafe/domain/cafe/ImagesTest.java
  server/src/test/java/com/project/yozmcafe/domain/member/MemberTest.java
  server/src/test/java/com/project/yozmcafe/service/MemberServiceTest.java
  server/src/test/java/com/project/yozmcafe/service/auth/JwtTokenProviderTest.java
Labels: BE, 우선순위:🟡보통, 카테고리:리팩토링🪚

#229 왼쪽, 오른쪽 이미지를 미리 불러와 이미지 로딩을 개선한다.
  client/src/components/CafeCard.tsx
Labels: 카테고리:기능🛠️, FE, FE:홈화면, 우선순위:🟡보통

#133 백엔드 Dockerfile 추가 및 docker-compose.yml service 추가
  .gitignore
  server/.env.example
  server/Dockerfile
  server/docker-compose.yml
Labels: BE, 카테고리:인프라🏗️, 우선순위:🟢낮음

#246 브라우저에 포커스가 다시 돌아왔을 때 메인 화면의 전체 데이터가 refetch되는 오류 수정
  client/src/hooks/useCafes.ts
Labels: 카테고리:버그👾, FE, FE:홈화면

#252 상세 모달 콘텐츠의 정렬을 맞춘다.
  client/src/components/CafeDetailBottomSheet.tsx
  client/src/components/OpeningHoursDetail.tsx
Labels: FE, FE:홈화면, 우선순위:🟠높음, 카테고리:리팩토링🪚

#259 server/docker-compose.yml 파일의 spring container 설정을 client/docker-compose.yml로 옮김
  client/docker-compose.yml
  server/docker-compose.yml
Labels: 카테고리:인프라🏗️

#253 access token이 만료되었을 때 자동으로 refresh되도록 구현
  client/src/client.ts
  client/src/context/AuthContext.tsx
  client/src/mocks/handlers.ts
Labels: 카테고리:기능🛠️, FE, 우선순위:🟡보통

#244 LikedCafe 코드 분리
  server/src/main/java/com/project/yozmcafe/controller/CafeController.java
  server/src/main/java/com/project/yozmcafe/controller/LikedCafeController.java
  server/src/main/java/com/project/yozmcafe/controller/MemberController.java
  server/src/main/java/com/project/yozmcafe/domain/member/Member.java
  server/src/main/java/com/project/yozmcafe/domain/member/MemberRepository.java
  server/src/main/java/com/project/yozmcafe/service/LikedCafeService.java
  server/src/main/java/com/project/yozmcafe/service/MemberService.java
  server/src/test/java/com/project/yozmcafe/controller/MemberControllerTest.java
  server/src/test/java/com/project/yozmcafe/domain/member/MemberRepositoryTest.java
  server/src/test/java/com/project/yozmcafe/domain/member/MemberTest.java
  server/src/test/java/com/project/yozmcafe/service/LikedCafeServiceTest.java
  server/src/test/java/com/project/yozmcafe/service/MemberServiceTest.java
Labels: BE, 우선순위:🟡보통, 카테고리:리팩토링🪚

#269 access token 재발급 실패 시 access token을 삭제하도록 처리
  client/src/client.ts
Labels: 카테고리:버그👾, FE, 우선순위:🔴긴급

#275 쿠키의 경로를 루트로 설정한다.
  server/src/main/java/com/project/yozmcafe/controller/auth/AuthController.java
Labels: 카테고리:버그👾, BE, 우선순위:🔴긴급

#272 한번 조회 처리한 카페에 대해 다시 조회 처리 되지 않도록 수정
  client/src/hooks/useCafeActions.ts
Labels: 카테고리:버그👾, FE, FE:홈화면, 우선순위:🟠높음

#273 흰색 그라데이션이 의도치 않은 상황에서 표시되는 오류 수정
  client/src/components/CafeDetailBottomSheet.tsx
Labels: 카테고리:버그👾, FE, FE:홈화면, 우선순위:🟡보통

#276 react-query-devtools 추가
  client/package.json
  client/src/App.tsx
  client/yarn.lock
Labels: FE, FE:홈화면, 우선순위:🟢낮음, 카테고리:테스트⚗️

#283 웹 접근성 개선 및 도입
  client/src/components/CafeCard.tsx
  client/src/components/CafeDetailBottomSheet.tsx
  client/src/components/CafeSummary.tsx
  client/src/components/LikeButton.tsx
  client/src/components/LoginModal.tsx
  client/src/components/Logo.tsx
  client/src/components/Navbar.tsx
  client/src/components/OpeningHoursDetail.tsx
Labels: 카테고리:기능🛠️, FE

#285 좋아요 버튼의 좋아요 상태가 독립적으로 관리되는 문제 수정
  client/src/components/LikeButton.tsx
Labels: 카테고리:버그👾, FE, FE:홈화면, 우선순위:🔴긴급

#301 협의한 컨벤션에 따라 리팩토링
  client/.eslintrc.json
  client/.prettierrc.json
  client/package.json
  client/src/client.ts
  client/src/components/Button.tsx
  client/src/components/CafeActionBar.tsx
  client/src/components/CafeCard.tsx
  client/src/components/CafeDetailBottomSheet.tsx
  client/src/components/CafeSummary.tsx
  client/src/components/LikeButton.tsx
  client/src/components/LikedCafeList.tsx
  client/src/components/LoginButton.tsx
  client/src/components/LoginModal.tsx
  client/src/components/Logo.tsx
  client/src/components/OpeningHoursDetail.tsx
  client/src/components/ProfileInfo.tsx
  client/src/context/AuthContext.tsx
  client/src/data/mockData.ts
  client/src/hooks/useAuth.ts
  client/src/hooks/useCafeActions.ts
  client/src/hooks/useIntersection.ts
  client/src/hooks/usePersistedState.ts
  client/src/mocks/handlers.ts
  client/src/pages/Auth.tsx
  client/src/pages/MyProfile.tsx
  client/yarn.lock
Labels: FE, 우선순위:🟠높음, 카테고리:리팩토링🪚

#288 스와이프를 통해 카페의 좌우 사진을 볼 수 있도록 한다.
  client/src/components/CafeCard.tsx
  client/src/components/CafeDetailBottomSheet.tsx
  client/src/components/LikedCafeList.tsx
  client/src/pages/Home.tsx
  client/src/styles/GlobalStyle.ts
  client/src/styles/theme.ts
Labels: 카테고리:기능🛠️, FE, FE:홈화면, 우선순위:🟠높음

#306 RestDocs 적용
  server/build.gradle
  server/src/test/java/com/project/yozmcafe/controller/BaseControllerTest.java
  server/src/test/java/com/project/yozmcafe/controller/MemberControllerTest.java
Labels: BE, 카테고리:문서🗎, 우선순위:🟠높음

#286 카페 CRUD 어드민 API 구현
  .gitignore
  server/src/main/java/com/project/yozmcafe/controller/CafeAdminController.java
  server/src/main/java/com/project/yozmcafe/controller/CafeController.java
  server/src/main/java/com/project/yozmcafe/controller/dto/cafe/AvailableTimeRequest.java
  server/src/main/java/com/project/yozmcafe/controller/dto/cafe/CafeRequest.java
  server/src/main/java/com/project/yozmcafe/controller/dto/cafe/CafeUpdateRequest.java
  server/src/main/java/com/project/yozmcafe/controller/dto/cafe/DetailRequest.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/Cafe.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/Detail.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/Images.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/LikedCafe.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/available/AvailableTime.java
  server/src/main/java/com/project/yozmcafe/domain/member/Member.java
  server/src/main/java/com/project/yozmcafe/exception/ErrorCode.java
  server/src/main/java/com/project/yozmcafe/service/CafeAdminService.java
  server/src/main/java/com/project/yozmcafe/service/CafeService.java
  server/src/main/java/com/project/yozmcafe/service/LikedCafeService.java
  server/src/test/java/com/project/yozmcafe/controller/CafeAdminControllerTest.java
  server/src/test/java/com/project/yozmcafe/domain/cafe/CafeTest.java
  server/src/test/java/com/project/yozmcafe/domain/cafe/DetailTest.java
  server/src/test/java/com/project/yozmcafe/domain/cafe/available/AvailableTimeTest.java
  server/src/test/java/com/project/yozmcafe/service/CafeAdminServiceTest.java
Labels: 카테고리:기능🛠️, BE

#314 authControllerTest, likedCafeControllerTest 문서화
  server/src/test/java/com/project/yozmcafe/controller/AuthControllerTest.java
  server/src/test/java/com/project/yozmcafe/controller/LikedCafeControllerTest.java
  server/src/test/java/com/project/yozmcafe/controller/MemberControllerTest.java
  server/src/test/java/com/project/yozmcafe/service/auth/OAuthProviderTest.java
Labels: BE, 우선순위:🟡보통

#312 Admin API RestDocs 적용
  server/build.gradle
  server/src/main/java/com/project/yozmcafe/controller/dto/cafe/AvailableTimeRequest.java
  server/src/main/java/com/project/yozmcafe/controller/dto/cafe/CafeUpdateRequest.java
  server/src/main/java/com/project/yozmcafe/controller/dto/cafe/DetailResponse.java
  server/src/test/java/com/project/yozmcafe/controller/CafeAdminControllerTest.java
Labels: BE, 우선순위:🟠높음

#318 likedCafesPaging 검증 추가
  server/src/main/java/com/project/yozmcafe/controller/LikedCafeController.java
  server/src/main/java/com/project/yozmcafe/domain/member/Member.java
  server/src/main/java/com/project/yozmcafe/service/LikedCafeService.java
  server/src/test/java/com/project/yozmcafe/domain/member/MemberTest.java
  server/src/test/java/com/project/yozmcafe/service/LikedCafeServiceTest.java
Labels: BE, 우선순위:🔴긴급

#320 좋아요 목록의 감지를 스크롤 이벤트가 아닌 useIntersection으로 수정한다.
  client/src/components/CafeCard.tsx
  client/src/components/LikedCafeList.tsx
  client/src/pages/Home.tsx
  client/src/pages/MyProfile.tsx
Labels: FE, FE:프로필 화면, 우선순위:🟠높음, 카테고리:리팩토링🪚

#329 백엔드의 history API 호출 코드 삭제
  client/src/client.ts
  client/src/hooks/useCafeActions.ts
  client/src/pages/Home.tsx
Labels: FE, FE:홈화면, 우선순위:🟠높음

#330 카페 단 건 조회 API 개발 - 공유하기
  server/src/main/java/com/project/yozmcafe/controller/CafeController.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/CafeRepository.java
  server/src/main/java/com/project/yozmcafe/service/CafeService.java
  server/src/test/java/com/project/yozmcafe/controller/CafeControllerTest.java
  server/src/test/java/com/project/yozmcafe/service/CafeServiceTest.java
Labels: 카테고리:기능🛠️, BE, 우선순위:🟡보통

#338 storybook이 프로젝트의 webpack.config.js의 설정을 사용하도록 설정
  client/.storybook/webpack.config.js
  client/package.json
  client/yarn.lock
Labels: FE, 우선순위:🟡보통, 카테고리:테스트⚗️

#339 프론트엔드 PR 테스트를 위한 github actions workflow 추가
  .github/workflows/client-deploy-storybook.yml
  .github/workflows/client-test.yml
Labels: FE, 카테고리:인프라🏗️, 우선순위:🟡보통

#356 dev 브랜치에서도 PR 테스트를 하도록 수정
  .github/workflows/client-deploy-storybook.yml
  .github/workflows/client-test.yml
Labels: FE, 카테고리:인프라🏗️, 우선순위:🟡보통, 카테고리:테스트⚗️

#342 client의 미사용 API 제거
  client/src/client.ts
Labels: FE, 우선순위:🟢낮음, 카테고리:리팩토링🪚

#343 react-refresh 적용
  client/babel.config.json
  client/package.json
  client/webpack.config.js
  client/webpack.prod.js
  client/yarn.lock
Labels: FE, 제안🙏, 우선순위:🟢낮음

#334 카페 좋아요 목록에 나열된 카페의 상세 내용을 볼 수 있게 한다.
  client/src/client.ts
  client/src/components/CafeActionBar.tsx
  client/src/components/LikedCafeList.tsx
  client/src/hooks/useCafeLikes.ts
  client/src/hooks/useLikedCafesDetail.ts
  client/src/mocks/handlers.ts
  client/src/pages/LikedCafeDetail.tsx
  client/src/router.tsx
Labels: 카테고리:기능🛠️, FE, FE:프로필 화면, 우선순위:🟠높음

#349 좋아요 순으로 랭킹을 보여주는 페이지를 제작한다.
  client/src/client.ts
  client/src/components/Button.tsx
  client/src/components/Logo.tsx
  client/src/components/Navbar.tsx
  client/src/components/RankCard.tsx
  client/src/data/mockData.ts
  client/src/hooks/useRank.ts
  client/src/mocks/handlers.ts
  client/src/pages/Rank.tsx
  client/src/router.tsx
  client/src/styles/theme.ts
  client/src/types/index.ts
Labels: 카테고리:기능🛠️, FE, 우선순위:🟠높음, FE:좋아요 랭킹 화면

#353 프로필 페이지의 좋아요 리스트를 연속적으로 불러오는 버그를 수정한다.
  client/src/components/LikedCafeList.tsx
  client/src/mocks/handlers.ts
Labels: 카테고리:버그👾, FE, FE:프로필 화면, 우선순위:🟠높음

#340 공유하기 기능을 구현한다.
  client/index.html
  client/src/client.ts
  client/src/components/CafeActionBar.tsx
  client/src/components/LikeButton.tsx
  client/src/components/ShareButton.tsx
  client/src/hooks/useCafe.ts
  client/src/mocks/handlers.ts
  client/src/pages/Cafe.tsx
  client/src/router.tsx
Labels: 카테고리:기능🛠️, FE, FE:홈화면, 우선순위:🟠높음

#341 메뉴 조회 기능 추가
  server/src/main/java/com/project/yozmcafe/controller/MenuController.java
  server/src/main/java/com/project/yozmcafe/controller/dto/menu/MenuBoardResponse.java
  server/src/main/java/com/project/yozmcafe/controller/dto/menu/MenuItemResponse.java
  server/src/main/java/com/project/yozmcafe/controller/dto/menu/MenuResponse.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/Cafe.java
  server/src/main/java/com/project/yozmcafe/domain/menu/Menu.java
  server/src/main/java/com/project/yozmcafe/domain/menu/MenuBoard.java
  server/src/main/java/com/project/yozmcafe/domain/menu/MenuBoardRepository.java
  server/src/main/java/com/project/yozmcafe/domain/menu/MenuRepository.java
  server/src/main/java/com/project/yozmcafe/exception/ErrorCode.java
  server/src/main/java/com/project/yozmcafe/service/CafeAdminService.java
  server/src/main/java/com/project/yozmcafe/service/MenuService.java
  server/src/main/resources/schema.sql
  server/src/test/java/com/project/yozmcafe/controller/MenuControllerTest.java
  server/src/test/java/com/project/yozmcafe/domain/menu/MenuBoardTest.java
  server/src/test/java/com/project/yozmcafe/domain/menu/MenuTest.java
  server/src/test/java/com/project/yozmcafe/service/MenuServiceTest.java
Labels: 카테고리:기능🛠️, BE, 우선순위:🟠높음

#335 회원의 좋아요 된 카페들의 상세정보를 조회하는 API 개발
  server/src/main/java/com/project/yozmcafe/YozmCafeApplication.java
  server/src/main/java/com/project/yozmcafe/controller/LikedCafeController.java
  server/src/main/java/com/project/yozmcafe/controller/dto/LikedCafeResponse.java
  server/src/main/java/com/project/yozmcafe/controller/dto/cafe/LikedCafeResponse.java
  server/src/main/java/com/project/yozmcafe/controller/dto/cafe/LikedCafeThumbnailResponse.java
  server/src/main/java/com/project/yozmcafe/domain/BaseEntity.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/LikedCafe.java
  server/src/main/java/com/project/yozmcafe/domain/member/Member.java
  server/src/main/java/com/project/yozmcafe/service/LikedCafeService.java
  server/src/main/resources/schema.sql
  server/src/test/java/com/project/yozmcafe/controller/LikedCafeControllerTest.java
  server/src/test/java/com/project/yozmcafe/domain/member/MemberTest.java
  server/src/test/java/com/project/yozmcafe/service/LikedCafeServiceTest.java
Labels: 카테고리:기능🛠️, BE, 우선순위:🟠높음

#350 카페 메뉴 보기 기능 구현
  client/public/images/cafe-menu-board-image-1.jpg
  client/public/images/cafe-menu-board-image-2.jpg
  client/public/images/cafe-menu-board-image-3.jpg
  client/public/images/cafe-menu-image-1.jpg
  client/public/images/cafe-menu-image-2.avif
  client/src/client.ts
  client/src/components/CafeActionBar.tsx
  client/src/components/CafeCard.tsx
  client/src/components/CafeDetailBottomSheet.tsx
  client/src/components/CafeMenuBottomSheet.tsx
  client/src/components/CafeMenuList.stories.tsx
  client/src/components/CafeMenuList.tsx
  client/src/components/CafeMenuMiniList.stories.tsx
  client/src/components/CafeMenuMiniList.tsx
  client/src/components/ImageModal.stories.tsx
  client/src/components/ImageModal.tsx
  client/src/data/mockData.ts
  client/src/hooks/useCafeMenus.ts
  client/src/index.tsx
  client/src/mocks/handlers.ts
  client/src/styles/GlobalStyle.ts
  client/src/types/index.ts
Labels: 카테고리:기능🛠️, FE, FE:홈화면, 우선순위:🟠높음

#351 어드민 API 이미지 업로드 기능 추가
  server/build.gradle
  server/src/main/java/com/project/yozmcafe/config/S3Configuration.java
  server/src/main/java/com/project/yozmcafe/controller/CafeAdminController.java
  server/src/main/java/com/project/yozmcafe/controller/dto/cafe/CafeRequest.java
  server/src/main/java/com/project/yozmcafe/controller/dto/cafe/CafeUpdateRequest.java
  server/src/main/java/com/project/yozmcafe/domain/S3Client.java
  server/src/main/java/com/project/yozmcafe/domain/resizedimage/ImageName.java
  server/src/main/java/com/project/yozmcafe/domain/resizedimage/ImageResizer.java
  server/src/main/java/com/project/yozmcafe/domain/resizedimage/ResizedImage.java
  server/src/main/java/com/project/yozmcafe/domain/resizedimage/Size.java
  server/src/main/java/com/project/yozmcafe/exception/ErrorCode.java
  server/src/main/java/com/project/yozmcafe/service/CafeAdminService.java
  server/src/main/java/com/project/yozmcafe/service/ImageService.java
  server/src/main/resources/application.properties
  server/src/test/java/com/project/yozmcafe/controller/CafeAdminControllerTest.java
  server/src/test/java/com/project/yozmcafe/domain/ImageNameTest.java
  server/src/test/java/com/project/yozmcafe/domain/ImageResizerTest.java
  server/src/test/java/com/project/yozmcafe/domain/SizeTest.java
  server/src/test/java/com/project/yozmcafe/service/CafeAdminServiceTest.java
  server/src/test/java/com/project/yozmcafe/service/ImageServiceTest.java
  server/src/test/resources/image.png
Labels: 카테고리:기능🛠️, BE

#360 지원 대상 브라우저를 browserslist 쿼리로 설정 및 lint(eslint, stylelint) 연동
  client/.browserslistrc
  client/.eslintrc.json
  client/.stylelintrc.json
  client/.vscode/extensions.json
  client/package.json
  client/yarn.lock
Labels: FE, 우선순위:🟡보통

#348 좋아요 랭킹 순으로 카페 정보 조회하는 API 개발
  server/src/main/java/com/project/yozmcafe/controller/CafeController.java
  server/src/main/java/com/project/yozmcafe/controller/dto/cafe/CafeRankResponse.java
  server/src/main/java/com/project/yozmcafe/domain/CafeRankGenerator.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/CafeRepository.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/Detail.java
  server/src/main/java/com/project/yozmcafe/exception/ErrorCode.java
  server/src/main/java/com/project/yozmcafe/service/CafeService.java
  server/src/test/java/com/project/yozmcafe/controller/CafeControllerTest.java
  server/src/test/java/com/project/yozmcafe/service/CafeRankGeneratorTest.java
  server/src/test/java/com/project/yozmcafe/service/CafeServiceTest.java
Labels: 카테고리:기능🛠️, BE, 우선순위:🟠높음

#365 좋아요 랭킹에서 카페를 누르면 해당 카페에 대한 상세 정보가 안나오는 현상을 수정한다.
  client/src/components/RankCard.tsx
Labels: 카테고리:버그👾, FE, 우선순위:🟠높음, FE:좋아요 랭킹 화면

#367 Cypress 설정 및 기본적인 E2E 테스팅 추가
  .github/workflows/client-test.yml
  client/.gitignore
  client/cypress.config.ts
  client/cypress/e2e/scroll-cafes.cy.ts
  client/cypress/support/commands.ts
  client/cypress/support/e2e.ts
  client/package.json
  client/tsconfig.json
  client/yarn.lock
Labels: FE, 작업:페어, 우선순위:🟡보통, 카테고리:테스트⚗️

#369 좋아요 버튼이 화면에서 작동이 안되는 부분을 해결한다.
  client/src/components/CafeActionBar.tsx
Labels: 카테고리:버그👾, FE, FE:홈화면, 우선순위:🟠높음

#373 Open API Specification GitHub Actions + Pages 자동 배포 설정
  .github/workflows/api-openapi-generate.yml
  .github/workflows/client-deploy-storybook.yml
  api/index.html
Labels: 카테고리:문서🗎, 우선순위:🟠높음

#375 menu/menuboard 추가 api 구현
  server/src/main/java/com/project/yozmcafe/controller/CafeAdminController.java
  server/src/main/java/com/project/yozmcafe/controller/dto/cafe/MenuBoardRequest.java
  server/src/main/java/com/project/yozmcafe/controller/dto/cafe/MenuRequest.java
  server/src/main/java/com/project/yozmcafe/service/ImageService.java
  server/src/main/java/com/project/yozmcafe/service/MenuService.java
  server/src/test/java/com/project/yozmcafe/service/ImageServiceTest.java
Labels: BE, 우선순위:🔴긴급

#371 이미지 url에 prefix를 추가한다.
  client/src/components/CafeCard.tsx
  client/src/components/LikedCafeList.tsx
  client/src/environment.ts
Labels: 카테고리:기능🛠️, FE, FE:홈화면, FE:프로필 화면, 우선순위:🟠높음

#378 GitHub Actions Open API Specification 자동 배포 경로 설정 오류 수정
  .github/workflows/api-openapi-generate.yml
Labels: 카테고리:문서🗎, 우선순위:🟠높음

#384 fix: Scale 방식 변경 fast -> smooth
  server/src/main/java/com/project/yozmcafe/domain/resizedimage/ImageResizer.java
Labels: BE, 우선순위:🔴긴급

#390 메뉴 추가할 때 이미지 multipartFile 없어도 가능하도록 수정
  server/src/main/java/com/project/yozmcafe/controller/CafeAdminController.java
  server/src/main/java/com/project/yozmcafe/controller/dto/cafe/MenuRequest.java
  server/src/main/java/com/project/yozmcafe/service/MenuService.java
Labels: BE, 우선순위:🔴긴급

#392 원본 사이즈로 리사이즈 로직 제거
  server/src/main/java/com/project/yozmcafe/controller/CafeAdminController.java
  server/src/main/java/com/project/yozmcafe/domain/resizedimage/ImageResizer.java
  server/src/main/java/com/project/yozmcafe/domain/resizedimage/Size.java
  server/src/main/java/com/project/yozmcafe/service/ImageService.java
  server/src/main/resources/application.properties
  server/src/test/java/com/project/yozmcafe/domain/ImageResizerTest.java
  server/src/test/java/com/project/yozmcafe/domain/SizeTest.java
  server/src/test/java/com/project/yozmcafe/service/ImageServiceTest.java
Labels: BE, 우선순위:🔴긴급

#393 백엔드 history API를 제거한다
  server/src/main/java/com/project/yozmcafe/controller/UnViewedCafeController.java
  server/src/main/java/com/project/yozmcafe/domain/member/Member.java
  server/src/main/java/com/project/yozmcafe/service/UnViewedCafeService.java
  server/src/test/java/com/project/yozmcafe/domain/member/MemberTest.java
  server/src/test/java/com/project/yozmcafe/service/CafeAdminServiceTest.java
  server/src/test/java/com/project/yozmcafe/service/UnViewedCafeServiceTest.java
Labels: BE, 우선순위:🔴긴급

#401 Open API Specification (openapi.yaml) 배포 오류 수정 (`echo` -> `cat`)
  .github/workflows/api-openapi-generate.yml
Labels: 카테고리:문서🗎, 우선순위:🟠높음

#398 좋아요 버튼을 눌렀을 때 카운트가 올라가지 않는 버그 수정
  client/src/components/CafeActionBar.tsx
Labels: 카테고리:버그👾, FE, FE:홈화면, 우선순위:🔴긴급

#404 마우스 포인트가 하단에 있을 때, 좌우 스와이프가 작동하지 않는다.
  client/src/components/CafeActionBar.tsx
  client/src/components/CafeCard.tsx
  client/src/components/CafeSummary.tsx
Labels: 카테고리:버그👾, FE, FE:홈화면, 우선순위:🟠높음

#399 메뉴 바텀시트가 뷰포트를 넘어가는 오류 수정
  client/src/components/CafeMenuBottomSheet.tsx
Labels: 카테고리:버그👾, FE, FE:홈화면, 우선순위:🟠높음

#402 메뉴/메뉴판 이미지 src, backgroundUrl prefix
  client/src/components/CafeCard.tsx
  client/src/components/CafeMenuBottomSheet.tsx
  client/src/components/CafeMenuList.tsx
  client/src/components/CafeMenuMiniList.tsx
  client/src/components/LikedCafeList.tsx
  client/src/components/RankCard.tsx
  client/src/environment.ts
  client/src/utils/Image.ts
Labels: FE, 우선순위:🔴긴급

#406 좋아요한 카페 목록 이미지 스타일 수정
  client/src/components/LikedCafeList.tsx
Labels: FE, FE:프로필 화면, 우선순위:🟠높음, 카테고리:리팩토링🪚

#408 잘못된 import 경로 수정
  client/src/components/CafeCard.tsx
  client/src/components/CafeMenuBottomSheet.tsx
  client/src/components/CafeMenuList.tsx
  client/src/components/CafeMenuMiniList.tsx
  client/src/components/LikedCafeList.tsx
  client/src/components/RankCard.tsx
Labels: 카테고리:버그👾, FE, 우선순위:🟠높음

#412 cypress-io/github-action@v5 사용하여 E2E 테스팅하도록 수정
  .github/workflows/client-test.yml
  client/package.json
Labels: 카테고리:버그👾, FE, 우선순위:🟠높음, 카테고리:테스트⚗️

#416 메뉴판 이미지가 안 나타나는 오류 수정
  client/src/components/CafeCard.tsx
  client/src/components/CafeMenuBottomSheet.tsx
  client/src/components/CafeMenuList.tsx
  client/src/components/CafeMenuMiniList.tsx
  client/src/components/ImageModal.tsx
  client/src/components/LikedCafeList.tsx
  client/src/components/RankCard.tsx
  client/src/environment.ts
Labels: 카테고리:버그👾, FE, FE:홈화면, 우선순위:🔴긴급

#418 랭킹 페이지에서 에러가 호출되는 문제를 해결한다.
  client/src/hooks/useRank.ts
Labels: 카테고리:버그👾, FE, 우선순위:🟠높음, FE:좋아요 랭킹 화면

#420 메뉴판 이미지로 보기 버튼에 이미지가 표시되지 않는 오류 수정
  client/src/components/CafeMenuBottomSheet.tsx
Labels: 카테고리:버그👾, FE, FE:홈화면, 우선순위:🟠높음

#425 주요 인프라 구성 코드화 (CI/CD, Prod 환경)
  .teamcity/README.md
  .teamcity/pom.xml
  .teamcity/settings.kts
  infrastructure/README.md
  infrastructure/ci/database.properties
  infrastructure/ci/docker-compose.yml
  infrastructure/ci/webhook-broker/app.js
  infrastructure/ci/webhook-broker/types.d.ts
  infrastructure/prod/docker-compose.yml
  infrastructure/prod/nginx.conf.template
Labels: 카테고리:문서🗎, 카테고리:인프라🏗️, 우선순위:🟢낮음
