Repository woowacourse-teams/2023-yozm-cafe, pull requests merged in 2023-07, with the labels that each got.

#22 API Client 추상화
  client/src/client.ts
Labels: 🌟 기능 🌟, 🌞 프론트엔드 🌞, 몹 프로그래밍

#24 CSS를 `createGlobalStyle` 로 변경
  client/package.json
  client/src/App.tsx
  client/src/styles/GlobalStyle.ts
  client/src/styles/ResetStyle.ts
  client/src/styles/base.css
  client/src/styles/index.css
  client/src/styles/reset.css
  client/webpack.config.js
  client/yarn.lock
Labels: 🌟 기능 🌟, 🌞 프론트엔드 🌞

#26 CODEOWNERS 설정
  .github/CODEOWNERS
Labels: 🙏 제안 🙏, 🗎 문서 🗎

#29 카페 정보에 대한 모달 컴포넌트 생성
  client/src/components/CafeInfoModal.stories.tsx
  client/src/components/CafeInfoModal.tsx
  client/src/pages/Home.tsx
  client/src/styles/theme.ts
Labels: 🌟 기능 🌟, 🌞 프론트엔드 🌞, 프론트엔드: 홈화면

#31 fix: Module not found 에러 해결
  client/src/index.tsx
Labels: 👾 버그 👾, 🌞 프론트엔드 🌞

#32 서버 워크플로우 디렉토리 `server/**`로 한정
  .github/workflows/gradle-publish.yml
Labels: 🌸 백엔드 🌸, 🙏 제안 🙏, 🏗️ 인프라 🏗️

#38 네비게이션 컴포넌트 생성
  client/src/components/BottomNavbar.tsx
  client/src/components/Navbar.stories.tsx
  client/src/components/Navbar.tsx
  client/src/pages/Home.tsx
  client/src/styles/theme.ts
Labels: 🌟 기능 🌟, 🌞 프론트엔드 🌞, 프론트엔드: 홈화면

#37 댓글 버튼과 공유하기 버튼 컴포넌트 생성
  client/src/components/CommentButton.stories.tsx
  client/src/components/CommentButton.tsx
  client/src/components/ShareButton.stories.tsx
  client/src/components/ShareButton.tsx
  client/src/pages/Home.tsx
Labels: 🌟 기능 🌟, 🌞 프론트엔드 🌞, 프론트엔드: 홈화면

#41 webpack open browser 옵션 추가 #40
  client/webpack.config.js
Labels: 🌞 프론트엔드 🌞, 🙏 제안 🙏

#46 스토리북 리액트 라우터 돔과 CSS 관련된 환경 설정하기
  client/.storybook/main.ts
  client/.storybook/preview.ts
  client/.storybook/preview.tsx
  client/package.json
  client/src/components/CafeInfoModal.tsx
  client/src/components/CommentButton.tsx
  client/src/components/ShareButton.tsx
  client/src/pages/Home.tsx
  client/yarn.lock
Labels: 🌞 프론트엔드 🌞

#43 좋아요를 추가와 취소 할 수 있는 기능
  client/src/components/LikeButton.stories.tsx
  client/src/components/LikeButton.tsx
  client/src/mocks/handlers.ts
  client/src/pages/Home.tsx
  client/src/types/index.ts
Labels: 🌟 기능 🌟, 🌞 프론트엔드 🌞, 프론트엔드: 홈화면

#45 공통으로 사용할 수 있는 버튼 컴포넌트와 로그인 페이지 UI 생성
  client/public/assets/google.svg
  client/public/assets/kakao.svg
  client/src/components/CafeInfoModal.tsx
  client/src/components/LoginButton.stories.tsx
  client/src/components/LoginButton.tsx
  client/src/components/Logo.stories.tsx
  client/src/components/Logo.tsx
  client/src/components/Navbar.tsx
  client/src/pages/Home.tsx
  client/src/pages/Login.tsx
  client/src/pages/Root.tsx
  client/src/styled-components.d.ts
  client/src/styles/GlobalStyle.ts
  client/src/styles/theme.ts
Labels: 🌟 기능 🌟, 🌞 프론트엔드 🌞, 프론트엔드: 로그인 화면

#57 스토리북 자동 빌드 및 배포 workflow 추가
  .github/workflows/storybook-deploy.yml
  client/.gitignore
Labels: 🌞 프론트엔드 🌞, 🏗️ 인프라 🏗️

#49 홈 화면 주요 기능 구현
  client/src/App.tsx
  client/src/client.ts
  client/src/components/AppHeader.tsx
  client/src/components/AsideActionBar.tsx
  client/src/components/CafeActionBar.tsx
  client/src/components/CafeCard.tsx
  client/src/components/CafeInfoModal.stories.tsx
  client/src/components/CafeInfoModal.tsx
  client/src/components/Card.tsx
  client/src/data/mockData.ts
  client/src/hooks/useCafes.ts
  client/src/hooks/useIntersection.ts
  client/src/mocks/handlers.ts
  client/src/pages/Home.tsx
  client/src/types/index.ts
Labels: 🌟 기능 🌟, 🌞 프론트엔드 🌞, 프론트엔드: 홈화면

#64 MySQL 플랫폼 ARM 아키텍처로 변경
  docker/docker-compose.yml
Labels: 👾 버그 👾, 🌸 백엔드 🌸

#65 네비게이션 바가 두 개 나타나는 현상 수정
  client/src/pages/Home.tsx
Labels: 👾 버그 👾, 🌞 프론트엔드 🌞, 프론트엔드: 홈화면

#67 client, server docker-compose.yml 설정
  client/docker-compose.yml
  client/nginx.conf
  server/docker-compose.yml
Labels: 🌸 백엔드 🌸, 🌞 프론트엔드 🌞, 🏗️ 인프라 🏗️

#59 카페정보 API 비회원인 경우의 기능 구현 & 회원별 보지 않은 카페정보 도메인 기능 개발
  server/build.gradle
  server/src/main/java/com/project/yozmcafe/config/PageConfiguration.java
  server/src/main/java/com/project/yozmcafe/controller/CafeController.java
  server/src/main/java/com/project/yozmcafe/controller/dto/cafe/AvailableTimeResponse.java
  server/src/main/java/com/project/yozmcafe/controller/dto/cafe/CafeResponse.java
  server/src/main/java/com/project/yozmcafe/controller/dto/cafe/DetailResponse.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/Cafe.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/CafeRepository.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/Detail.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/Images.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/UnViewedCafe.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/available/AvailableTime.java
  server/src/main/java/com/project/yozmcafe/domain/member/Member.java
  server/src/main/java/com/project/yozmcafe/domain/member/MemberRepository.java
  server/src/main/java/com/project/yozmcafe/service/CafeService.java
  server/src/test/java/com/project/yozmcafe/acceptance/CafeAcceptanceTest.java
  server/src/test/java/com/project/yozmcafe/domain/cafe/CafeRepositoryTest.java
  server/src/test/java/com/project/yozmcafe/fixture/Fixture.java
  server/src/test/java/com/project/yozmcafe/util/AcceptanceContext.java
  server/src/test/java/com/project/yozmcafe/util/UnViewedCafeRepository.java
Labels: 🌟 기능 🌟, 🌸 백엔드 🌸

#76 Feat/50 background shadow
  client/src/styles/GlobalStyle.ts
  client/src/styles/theme.ts
Labels: 🌟 기능 🌟, 🌞 프론트엔드 🌞

#75 OAuth2.0 기반 로그인 기능 개발
  server/build.gradle
  server/src/main/java/com/project/yozmcafe/config/WebMvcConfig.java
  server/src/main/java/com/project/yozmcafe/controller/LoginArgumentResolver.java
  server/src/main/java/com/project/yozmcafe/controller/MemberController.java
  server/src/main/java/com/project/yozmcafe/controller/StringToOAuthProviderConverter.java
  server/src/main/java/com/project/yozmcafe/controller/auth/AuthController.java
  server/src/main/java/com/project/yozmcafe/controller/auth/MemberInfo.java
  server/src/main/java/com/project/yozmcafe/controller/auth/OAuthProvider.java
  server/src/main/java/com/project/yozmcafe/controller/dto/MemberResponse.java
  server/src/main/java/com/project/yozmcafe/controller/dto/TokenResponse.java
  server/src/main/java/com/project/yozmcafe/domain/auth/token/GoogleToken.java
  server/src/main/java/com/project/yozmcafe/domain/auth/token/KakaoToken.java
  server/src/main/java/com/project/yozmcafe/domain/auth/token/OAuthToken.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/CafeRepository.java
  server/src/main/java/com/project/yozmcafe/domain/member/Member.java
  server/src/main/java/com/project/yozmcafe/domain/member/MemberRepository.java
  server/src/main/java/com/project/yozmcafe/service/MemberService.java
  server/src/main/java/com/project/yozmcafe/service/auth/AuthService.java
  server/src/main/java/com/project/yozmcafe/service/auth/GoogleOAuthClient.java
  server/src/main/java/com/project/yozmcafe/service/auth/JwtTokenProvider.java
  server/src/main/java/com/project/yozmcafe/service/auth/KakaoOAuthClient.java
  server/src/main/java/com/project/yozmcafe/service/auth/OAuthClient.java
  server/src/main/resources/application-test.properties
  server/src/main/resources/application.properties
  server/src/test/java/com/project/yozmcafe/controller/MemberControllerTest.java
  server/src/test/java/com/project/yozmcafe/controller/StringToOAuthProviderConverterTest.java
  server/src/test/java/com/project/yozmcafe/controller/auth/AuthControllerTest.java
  server/src/test/java/com/project/yozmcafe/controller/auth/OAuthProviderTest.java
  server/src/test/java/com/project/yozmcafe/domain/auth/token/OAuthTokenTest.java
  server/src/test/java/com/project/yozmcafe/domain/cafe/CafeRepositoryTest.java
  server/src/test/java/com/project/yozmcafe/domain/member/MemberRepositoryTest.java
  server/src/test/java/com/project/yozmcafe/service/MemberServiceTest.java
  server/src/test/java/com/project/yozmcafe/service/auth/AuthServiceTest.java
  server/src/test/java/com/project/yozmcafe/service/auth/JwtTokenProviderTest.java
  server/src/test/resources/application.properties
Labels: 🌟 기능 🌟, 🌸 백엔드 🌸

#78 NavBar와 LikedCafeList 컴포넌트 수정
  client/src/components/LikedCafeList.tsx
  client/src/components/Navbar.tsx
Labels: 🌟 기능 🌟, 🌞 프론트엔드 🌞

#81 잘못된 타입 import 수정: `Theme` 타입을 import하도록 변경
  client/src/styled-components.d.ts
Labels: 👾 버그 👾, 🌞 프론트엔드 🌞

#86 홈 화면의 카페 카드 사이에 불필요한 마진 삭제
  client/src/pages/Home.tsx
Labels: 🌟 기능 🌟, 🌞 프론트엔드 🌞, 프론트엔드: 홈화면

#84 홈 화면에서 스와이프 시 하나의 카드만 넘어갈 수 있게 수정
  client/src/pages/Home.tsx
Labels: 👾 버그 👾, 🌞 프론트엔드 🌞, 프론트엔드: 홈화면

#82 버튼의 크기, 색상 수정 그리고 시연을 위한 로직 수정
  client/src/components/CafeActionBar.tsx
  client/src/components/CommentButton.tsx
  client/src/components/LikeButton.stories.tsx
  client/src/components/LikeButton.tsx
  client/src/components/ShareButton.tsx
  client/src/pages/Login.tsx
Labels: 👾 버그 👾, 🌞 프론트엔드 🌞, 프론트엔드: 홈화면

#89 홈 화면의 오른쪽 버튼들(CafeActionBar) 디자인 개선
  client/src/components/CommentButton.tsx
  client/src/components/ShareButton.tsx
Labels: 🌟 기능 🌟, 🌞 프론트엔드 🌞, 프론트엔드: 홈화면

#90 OAuth Provider로 Redirect하는 기능
  server/src/main/java/com/project/yozmcafe/controller/auth/AuthController.java
  server/src/main/java/com/project/yozmcafe/controller/auth/OAuthProvider.java
  server/src/main/java/com/project/yozmcafe/service/auth/AuthService.java
  server/src/main/java/com/project/yozmcafe/service/auth/GoogleOAuthClient.java
  server/src/main/java/com/project/yozmcafe/service/auth/KakaoOAuthClient.java
  server/src/main/java/com/project/yozmcafe/service/auth/OAuthClient.java
  server/src/main/resources/application.properties
  server/src/test/java/com/project/yozmcafe/controller/auth/AuthControllerTest.java
  server/src/test/java/com/project/yozmcafe/controller/auth/OAuthProviderTest.java
  server/src/test/java/com/project/yozmcafe/service/auth/AuthServiceTest.java
Labels: 카테고리:기능🛠️, BE

#96 로그인 된 사용자에게 보여주는 카페정보에 좋아요 여부를 매핑하는 기능 구현
  server/src/main/java/com/project/yozmcafe/controller/dto/cafe/CafeResponse.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/Cafe.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/CafeRepository.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/LikedCafe.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/UnViewedCafe.java
  server/src/main/java/com/project/yozmcafe/domain/member/Member.java
  server/src/main/java/com/project/yozmcafe/service/CafeService.java
  server/src/test/java/com/project/yozmcafe/domain/member/MemberTest.java
  server/src/test/java/com/project/yozmcafe/fixture/Fixture.java
  server/src/test/java/com/project/yozmcafe/service/CafeServiceTest.java
Labels: 카테고리:기능🛠️, BE

#120 OAuth Redirect Uri 수정
  server/src/main/java/com/project/yozmcafe/service/auth/GoogleOAuthClient.java
  server/src/main/java/com/project/yozmcafe/service/auth/KakaoOAuthClient.java
  server/src/main/java/com/project/yozmcafe/service/auth/OAuthClient.java
Labels: BE

#121 MSW를 비활성화 할 수 있는 환경변수 추가
  client/README.md
  client/package.json
  client/src/environment.ts
  client/src/index.tsx
  client/webpack.config.js
  client/yarn.lock
Labels: 카테고리:기능🛠️, FE

#122 webpack devServer 프록시 설정 기능 추가
  client/README.md
  client/webpack.config.js
Labels: FE, 카테고리:인프라🏗️

#123 API 요청에 `/api` prefix가 붙도록 수정
  client/src/client.ts
  client/src/mocks/handlers.ts
  client/src/pages/Login.tsx
Labels: FE

#128 로그인 된 사용자에게 보여주는 카페정보에 좋아요 여부를 매핑하는 기능 구현 리뷰 반영
  server/src/main/java/com/project/yozmcafe/controller/CafeController.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/CafeRepository.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/LikedCafe.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/UnViewedCafe.java
  server/src/main/java/com/project/yozmcafe/service/CafeService.java
  server/src/test/java/com/project/yozmcafe/domain/member/MemberTest.java
  server/src/test/java/com/project/yozmcafe/service/CafeServiceTest.java
Labels: 카테고리:기능🛠️, BE, 우선순위:🟠높음

#141 accessToken의 Bearer 분리
  server/src/main/java/com/project/yozmcafe/controller/auth/AuthController.java
Labels: 카테고리:버그👾, BE

#100 회원, 비회원의 카페 정보 조회 API 개발
  server/src/main/java/com/project/yozmcafe/controller/CafeController.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/CafeRepository.java
  server/src/test/java/com/project/yozmcafe/acceptance/CafeAcceptanceTest.java
  server/src/test/java/com/project/yozmcafe/controller/CafeControllerTest.java
  server/src/test/java/com/project/yozmcafe/controller/MemberControllerTest.java
  server/src/test/java/com/project/yozmcafe/domain/cafe/CafeRepositoryTest.java
  server/src/test/java/com/project/yozmcafe/service/MemberServiceTest.java
  server/src/test/java/com/project/yozmcafe/service/auth/AuthServiceTest.java
Labels: 카테고리:기능🛠️, BE

#143 하단 네비게이션 바를 상단으로 옮기고 다시 디자인한다.
  client/src/components/Button.stories.tsx
  client/src/components/Button.tsx
  client/src/components/Navbar.tsx
  client/src/pages/MyProfile.tsx
  client/src/pages/Root.tsx
Labels: FE, 우선순위:🟡보통, 카테고리:리팩토링🪚

#134 프로필 기능 구현 (API 연동)
  client/src/components/Navbar.tsx
  client/src/pages/MyProfile.tsx
Labels: 카테고리:기능🛠️, FE, FE:홈화면, FE:프로필 화면

#140 좋아요와 관련된 기능 API 모킹
  client/src/mocks/handlers.ts
Labels: FE, 카테고리:테스트⚗️

#145 webpack typescript 타입 체킹 적용 (fork-ts-checker-webpack-plugin)
  client/package.json
  client/webpack.config.js
  client/yarn.lock
Labels: FE, 우선순위:🟢낮음

#148 `/cafes` API의 응답 데이터가 없을 때 fetch가 무한으로 일어나고 있는 오류 수정
  client/src/hooks/useCafes.ts
  client/src/pages/Home.tsx
Labels: 카테고리:버그👾, FE, FE:홈화면, 우선순위:🟡보통

#150 잘못된 `IS_DEV`, `MSW` 코드 수정
  client/src/environment.ts
Labels: 카테고리:버그👾, FE, 우선순위:🟠높음

#151 로그인 API 모킹이 JWT 형식의 access token을 응답하도록 수정
  client/src/mocks/handlers.ts
Labels: FE, 우선순위:🟡보통, 카테고리:테스트⚗️

#155 로그아웃 기능 구현
  client/src/client.ts
  client/src/hooks/useAuth.ts
  client/src/mocks/handlers.ts
  client/src/pages/MyProfile.tsx
Labels: 카테고리:기능🛠️, FE, FE:프로필 화면

#153 로그인 페이지를 홈화면에서 바로 로그인 할 수 있도록 모달 방식으로 리디자인한다.
  client/public/assets/kakao.svg
  client/src/components/LoginButton.stories.tsx
  client/src/components/LoginButton.tsx
  client/src/components/Logo.tsx
  client/src/components/Modal.stories.tsx
  client/src/components/Modal.tsx
  client/src/components/Navbar.tsx
  client/src/pages/Login.tsx
  client/src/router.tsx
  client/src/styles/theme.ts
Labels: FE, FE:로그인 화면, 우선순위:🟡보통

#159 회원 정보 조회 API 모킹
  client/src/mocks/handlers.ts
Labels: FE, 우선순위:🟠높음, 카테고리:테스트⚗️

#160 로그인/비로그인 상태에 따라 카페 목록 조회 API 호출 분기 처리
  client/src/client.ts
  client/src/hooks/useCafes.ts
  client/src/mocks/handlers.ts
  client/src/pages/Home.tsx
Labels: 카테고리:버그👾, 카테고리:기능🛠️, FE, FE:홈화면, 우선순위:🟠높음

#167 임시 카페 저장 API 개발
  server/src/main/java/com/project/yozmcafe/controller/CafeController.java
  server/src/main/java/com/project/yozmcafe/controller/dto/cafe/CafeRequest.java
  server/src/main/java/com/project/yozmcafe/controller/dto/cafe/DetailRequest.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/Cafe.java
  server/src/main/java/com/project/yozmcafe/service/CafeService.java
Labels: 카테고리:기능🛠️, BE, 우선순위:🟡보통

#152 좋아요 추가, 취소 API 개발
  server/src/main/java/com/project/yozmcafe/controller/CafeController.java
  server/src/main/java/com/project/yozmcafe/controller/LoginArgumentResolver.java
  server/src/main/java/com/project/yozmcafe/controller/auth/AuthController.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/Cafe.java
  server/src/main/java/com/project/yozmcafe/domain/member/Member.java
  server/src/main/java/com/project/yozmcafe/service/MemberService.java
  server/src/test/java/com/project/yozmcafe/controller/CafeControllerTest.java
  server/src/test/java/com/project/yozmcafe/controller/auth/AuthControllerTest.java
  server/src/test/java/com/project/yozmcafe/domain/cafe/CafeTest.java
  server/src/test/java/com/project/yozmcafe/domain/member/MemberTest.java
  server/src/test/java/com/project/yozmcafe/service/MemberServiceTest.java
Labels: 카테고리:기능🛠️, BE, 우선순위:🟡보통

#174 홈 화면의 모달 디자인을 개선한다.
  client/src/components/CafeActionBar.tsx
  client/src/components/CafeCard.tsx
  client/src/components/CafeInfoModal.tsx
  client/src/components/Navbar.tsx
Labels: FE, FE:홈화면

#165 요청 URI 로깅 필터 구현
  .gitignore
  server/src/main/java/com/project/yozmcafe/controller/LoggingFilter.java
  server/src/main/resources/application.properties
  server/src/main/resources/logback-spring.xml
Labels: 카테고리:기능🛠️, BE

#182 detail 객체 수정
  server/src/main/java/com/project/yozmcafe/controller/dto/cafe/DetailRequest.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/Detail.java
  server/src/test/java/com/project/yozmcafe/controller/auth/AuthControllerTest.java
  server/src/test/java/com/project/yozmcafe/fixture/Fixture.java
Labels: BE, 카테고리:리팩토링🪚

#170 redirectAuthorizationUri 제공 코드 수정
  server/src/main/java/com/project/yozmcafe/controller/auth/AuthController.java
  server/src/main/java/com/project/yozmcafe/controller/dto/AuthorizationUrlDto.java
  server/src/main/java/com/project/yozmcafe/service/auth/AuthService.java
  server/src/test/java/com/project/yozmcafe/controller/auth/AuthControllerTest.java
  server/src/test/java/com/project/yozmcafe/service/auth/AuthServiceTest.java
Labels: 카테고리:기능🛠️, BE

#183 영업시간의 형식 변경
  server/src/main/java/com/project/yozmcafe/controller/dto/cafe/AvailableTimeResponse.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/available/AvailableTime.java
  server/src/test/java/com/project/yozmcafe/fixture/Fixture.java
Labels: 카테고리:기능🛠️, BE, 우선순위:🟡보통

#162 좋아요 목록 조회 기능 구현
  server/src/main/java/com/project/yozmcafe/controller/MemberController.java
  server/src/main/java/com/project/yozmcafe/controller/dto/LikedCafeResponse.java
  server/src/main/java/com/project/yozmcafe/controller/dto/cafe/AvailableTimeResponse.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/Cafe.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/Images.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/available/AvailableTime.java
  server/src/main/java/com/project/yozmcafe/domain/member/MemberRepository.java
  server/src/main/java/com/project/yozmcafe/service/MemberService.java
  server/src/test/java/com/project/yozmcafe/controller/MemberControllerTest.java
  server/src/test/java/com/project/yozmcafe/controller/auth/AuthControllerTest.java
  server/src/test/java/com/project/yozmcafe/domain/cafe/CafeRepositoryTest.java
  server/src/test/java/com/project/yozmcafe/domain/cafe/ImagesTest.java
  server/src/test/java/com/project/yozmcafe/domain/member/MemberRepositoryTest.java
  server/src/test/java/com/project/yozmcafe/domain/member/MemberTest.java
  server/src/test/java/com/project/yozmcafe/fixture/Fixture.java
  server/src/test/java/com/project/yozmcafe/service/CafeHistoryServiceTest.java
  server/src/test/java/com/project/yozmcafe/service/CafeServiceTest.java
  server/src/test/java/com/project/yozmcafe/service/MemberServiceTest.java
  server/src/test/java/com/project/yozmcafe/util/UnViewedCafeRepository.java
  server/src/test/resources/truncate.sql
Labels: 카테고리:기능🛠️, BE

#164 새로운 멤버 저장 시 unviewedCafe들도 함께 저장하는 기능 구현
  server/src/main/java/com/project/yozmcafe/service/auth/AuthService.java
  server/src/test/java/com/project/yozmcafe/controller/auth/AuthControllerTest.java
  server/src/test/java/com/project/yozmcafe/service/auth/AuthServiceTest.java
Labels: 카테고리:기능🛠️, BE, 우선순위:🟠높음

#186 팀시티 자동 문제가 안되는 문제를 해결하고 로그인 모달의 크기를 수정한다.
  client/src/client.ts
  client/src/components/LoginModal.stories.tsx
  client/src/components/LoginModal.tsx
  client/src/components/Navbar.tsx
Labels: 카테고리:버그👾, FE, FE:로그인 화면, 우선순위:🟡보통

#189 테이블 컬럼 타입 수정
  server/src/main/java/com/project/yozmcafe/domain/cafe/Detail.java
  server/src/main/resources/application.properties
  server/src/main/resources/schema.sql
  server/src/test/java/com/project/yozmcafe/controller/CafeControllerTest.java
  server/src/test/java/com/project/yozmcafe/controller/auth/AuthControllerTest.java
  server/src/test/java/com/project/yozmcafe/controller/auth/OAuthProviderTest.java
  server/src/test/java/com/project/yozmcafe/service/auth/AuthServiceTest.java
Labels: BE, 우선순위:🔴긴급

#193 프로덕션 배포를 위한 웹팩 설정
  client/package.json
  client/webpack.prod.js
Labels: FE, 작업:몹, 카테고리:인프라🏗️

#195 변경된 카페 조회 API에 맞춰서 로직을 수정한다.
  client/src/components/CafeCard.tsx
  client/src/data/mockData.ts
  client/src/mocks/handlers.ts
  client/src/types/index.ts
Labels: 카테고리:버그👾, FE, FE:홈화면, 우선순위:🔴긴급

#177 메인 화면에서 카페 좋아요 추가 취소 기능 구현
  client/src/client.ts
  client/src/components/CafeActionBar.tsx
  client/src/components/CafeCard.tsx
  client/src/hooks/useCafeActions.ts
  client/src/mocks/handlers.ts
Labels: 카테고리:기능🛠️, FE, FE:홈화면, 우선순위:🟡보통

#184 카페 하나의 사진을 여러 장 볼 수 있는 기능
  client/src/components/CafeCard.tsx
  client/src/data/mockData.ts
Labels: 카테고리:기능🛠️, FE, FE:홈화면, 우선순위:🟠높음

#178 OAuth 페이지 URL을 API에서 받도록 하고, 모킹하여 백엔드 없이 로그인 플로우가 동작하도록 구현
  client/src/client.ts
  client/src/components/LoginModal.tsx
  client/src/components/Navbar.tsx
  client/src/hooks/useAuthUrls.ts
  client/src/mocks/handlers.ts
  client/src/pages/TestAuthorizationCode.tsx
  client/src/router.tsx
  client/src/types/index.ts
Labels: 카테고리:기능🛠️, FE, FE:홈화면, FE:로그인 화면, 우선순위:🟠높음, 카테고리:리팩토링🪚, 카테고리:테스트⚗️

#203 images.urls 잠수함 패치 대응
  client/src/components/CafeCard.tsx
Labels: 카테고리:버그👾, FE, 우선순위:🔴긴급

#173 좋아요한 카페 목록을 보여주도록 구현한다.
  client/src/client.ts
  client/src/components/LikedCafeList.tsx
  client/src/data/mockData.ts
  client/src/hooks/useLikedCafes.ts
  client/src/mocks/handlers.ts
  client/src/pages/MyProfile.tsx
  client/src/pages/Root.tsx
  client/src/types/index.ts
Labels: 카테고리:기능🛠️, FE, FE:프로필 화면, 우선순위:🟠높음

#199 로그인 버튼에서 프로필 버튼으로 전환 시 디자인 수정
  client/src/components/Button.stories.tsx
  client/src/components/Button.tsx
  client/src/components/Navbar.tsx
  client/src/pages/MyProfile.tsx
Labels: 카테고리:기능🛠️, FE, FE:홈화면, FE:프로필 화면, 우선순위:🟡보통

#205 fix: OAuthProvider Name 소문자로 출력되도록 수정
  server/src/main/java/com/project/yozmcafe/controller/auth/OAuthProvider.java
  server/src/main/java/com/project/yozmcafe/service/auth/AuthService.java
  server/src/test/java/com/project/yozmcafe/controller/auth/AuthControllerTest.java
  server/src/test/java/com/project/yozmcafe/controller/auth/OAuthProviderTest.java
Labels: 카테고리:버그👾, BE, 우선순위:🔴긴급

#206 홈화면에서 모달, 공유, 좋아요 아이콘의 크기와 모양을 수정한다.
  client/src/components/CafeActionBar.tsx
  client/src/components/CafeCard.tsx
  client/src/components/CafeInfoModal.tsx
  client/src/components/LikeButton.tsx
  client/src/components/ShareButton.tsx
Labels: FE, FE:홈화면, 우선순위:🟡보통, 카테고리:리팩토링🪚

#210 createGlobalStyle에서 사용하면 안되는 @import 구문을 제거한다.
  client/src/components/Button.tsx
  client/src/components/Navbar.tsx
  client/src/pages/MyProfile.tsx
  client/src/styles/GlobalStyle.ts
Labels: 카테고리:버그👾, FE, FE:홈화면, 우선순위:🔴긴급

#211 좋아요를 눌렀을 때 로그인이 안되어 있을 시 `로그인이 필요합니다` 문구를 띄우도록 수정
  client/src/components/CafeActionBar.tsx
  client/src/hooks/useCafeActions.ts
Labels: 카테고리:버그👾, FE, FE:홈화면

#212 카페를 스크롤 할 때 마다 확인(조회) 처리
  client/src/client.ts
  client/src/components/CafeCard.tsx
  client/src/hooks/useCafeActions.ts
  client/src/mocks/handlers.ts
  client/src/pages/Home.tsx
Labels: 카테고리:기능🛠️, FE, FE:홈화면, 작업:페어

#197 영업여부 false로 매핑되는 오류 해결
  server/src/main/java/com/project/yozmcafe/controller/dto/cafe/AvailableTimeRequest.java
  server/src/main/java/com/project/yozmcafe/controller/dto/cafe/DetailRequest.java
Labels: 카테고리:버그👾, BE, 우선순위:🟡보통

#214 카페 모달 상세정보 보는 기능 구현
  client/.storybook/preview.tsx
  client/src/components/CafeActionBar.tsx
  client/src/components/CafeCard.tsx
  client/src/components/CafeDetailBottomSheet.stories.tsx
  client/src/components/CafeDetailBottomSheet.tsx
  client/src/components/CafeInfoModal.stories.tsx
  client/src/components/CafeInfoModal.tsx
  client/src/components/CafeSummary.stories.tsx
  client/src/components/CafeSummary.tsx
  client/src/components/OpeningHoursDetail.tsx
  client/src/data/mockData.ts
  client/src/styles/ResetStyle.ts
  client/src/types/index.ts
Labels: 카테고리:기능🛠️, FE, FE:홈화면, 작업:몹

#216 likedCafes url을 변경한다.
  server/src/main/java/com/project/yozmcafe/controller/MemberController.java
  server/src/test/java/com/project/yozmcafe/controller/MemberControllerTest.java
Labels: BE

#221 로그인 상태에서만 카페 확인(조회) 처리되도록수정
  client/src/pages/Home.tsx
Labels: 카테고리:버그👾, FE, FE:홈화면, 우선순위:🟠높음

#222 현재 지원하지 않는 기능인 공유 버튼을 제거한다.
  client/src/components/CafeActionBar.tsx
  client/src/components/CafeCard.tsx
  client/src/components/ShareButton.stories.tsx
  client/src/components/ShareButton.tsx
Labels: FE, FE:홈화면, 우선순위:🔴긴급, 카테고리:리팩토링🪚

#223 프로필 화면의 사진을 정사각형으로 표시하도록 한다.
  client/src/components/LikedCafeList.tsx
Labels: FE, FE:프로필 화면, 카테고리:리팩토링🪚

#228 재로그인 시 db 삭제되는 문제 해결
  server/src/main/java/com/project/yozmcafe/service/auth/AuthService.java
  server/src/test/java/com/project/yozmcafe/controller/MemberControllerTest.java
Labels: 카테고리:버그👾, BE, 우선순위:🔴긴급

#192 회원 카페 조회 API - 이미 본 것 제외하고 랜덤한 페이지의 카페를 응답하는 기능 구현
  server/src/main/java/com/project/yozmcafe/controller/CafeController.java
  server/src/main/java/com/project/yozmcafe/controller/UnViewedCafeController.java
  server/src/main/java/com/project/yozmcafe/controller/dto/cafe/CafeResponse.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/CafeRepository.java
  server/src/main/java/com/project/yozmcafe/domain/cafe/UnViewedCafeRepository.java
  server/src/main/java/com/project/yozmcafe/service/CafeService.java
  server/src/main/java/com/project/yozmcafe/service/RandomPageRequestGenerator.java
  server/src/main/java/com/project/yozmcafe/service/UnViewedCafeService.java
  server/src/test/java/com/project/yozmcafe/domain/cafe/CafeRepositoryTest.java
  server/src/test/java/com/project/yozmcafe/service/CafeServiceTest.java
  server/src/test/java/com/project/yozmcafe/service/RandomPageRequestGeneratorTest.java
  server/src/test/java/com/project/yozmcafe/service/UnViewedCafeServiceTest.java
  server/src/test/java/com/project/yozmcafe/util/UnViewedCafeRepository.java
Labels: 카테고리:기능🛠️, BE, 우선순위:🔴긴급

#230 브라우저 창 타이틀과 아이콘 그리고 카카오톡 썸네일을 추가한다.
  client/index.html
  client/public/favicon.ico
  client/public/ios.png
  client/public/thumbnail-image.png
Labels: 카테고리:기능🛠️, FE, FE:홈화면, 우선순위:🟡보통

#243 상세 보기 모달에 닫기 버튼을 추가한다.
  client/src/components/CafeDetailBottomSheet.tsx
Labels: 카테고리:기능🛠️, FE, FE:홈화면, 우선순위:🟠높음

#240 좋아요 아이콘과 더보기 아이콘의 간격이 안맞는 부분을 수정한다.
  client/src/components/CafeActionBar.tsx
  client/src/styles/ResetStyle.ts
Labels: FE, FE:홈화면, 우선순위:🟠높음, 카테고리:리팩토링🪚
